### ISSUE TITLE
How to set only one kind of code format?

### ISSUE THREAD

**Issue by renanserrou** [rmtmckenzie/flutter_qr_mobile_vision#101]
Hello Im kind of new on the dev world, not sure if this is the right place to ask this question, but I couldn´t get what is the syntax to set a specific code format. Thx!

![formats](https://user-images.githubusercontent.com/34111487/63535856-7075d680-c4e0-11e9-968d-e629fabed307.jpg)

**Comment by abdussamad0** [comment]
**First Import this** 
`import 'package:qr_mobile_vision/qr_mobile_vision.dart';
`
...
...

`formats: [BarcodeFormats.CODE_93, BarcodeFormats.CODABAR, BarcodeFormats.DATA_MATRIX],`
 ...
