### ISSUE TITLE
Androidx

### ISSUE THREAD

**Issue by pboethig** [rmtmckenzie/flutter_qr_mobile_vision#102]
The Scanner runs exactly 1 Time after route and copme back the camera wont open.

This is the message:

I/cgr.qrmv.QrReader( 6311): Using new camera API.
I/cgr.qrmv.QrDetector( 6311): Making detector2 for formats: 0
W/DynamiteModule( 6311): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule( 6311): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 6311): Cannot load feature, fall back to load whole module.
W/DynamiteModule( 6311): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 6311): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2702
I/DynamiteModule( 6311): Selected remote version of com.google.android.gms.vision.dynamite, version >= 2702
V/DynamiteModule( 6311): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/Vision  ( 6311): Loading library libbarhopper.so
I/Vision  ( 6311): libbarhopper.so library load status: true
I/cgr.qrmv.QrCameraC2( 6311): Setting af mode to: 4

**Comment by DeBelg** [comment]
Where did you see this as a androidx issue?

**Comment by 7flash** [comment]
Have the same issue, any ideas?

**Comment by DeBelg** [comment]
Hi can you link me again?
Im on mobile and I’ll check

**Comment by 7flash** [comment]
@DeBelg :sos:

**Comment by DeBelg** [comment]
I remember not using this repo as it was not affective. Are you looking for
a QR scanner?

**Comment by rmtmckenzie** [comment]
The 1.0.0 release switches away from the GoogleMobileVision library to FirebaseMobileVision, which should resolve this issue. I'm closing this bug but if you want to give it a test and notice anything wrong, feedback would be appreciated =).
