### ISSUE TITLE
How to detect only a subarea of the camera?

### ISSUE THREAD

**Issue by LeandroMoura3** [rmtmckenzie/flutter_qr_mobile_vision#105]
I need to detect only in the top of the camera.

In this scenario, only top of the camera will be displayed for the user, the middle and bottom will be replaced by UI like a list. But, when the user use the QrCamera to scan the codes, all camera are in detect mode. So, the part that are replaced be the UI detect too. The result is that codes are detected even if they don't are showing in the camera of the user. I wanna fix this thing. Do anyone have any ideia?

Thanks.

**Comment by feliperfmarques** [comment]
Please, check properties `targetWidth` and `targetHeight `in `qr_camera.dart`. I think that this properties are used for setup recognation area in `QrReader `method in `QrReader.java`

**Comment by DavideBicego** [comment]
Have anybody got the chance to try what @feliperfmarques suggested?

**Comment by LeandroMoura3** [comment]
Hello.

I solve this problem in the function n21Buffer.put(...) localized in QrDetector2.java.
Here is the solution:
for (int i = imgHeight - finalDetectorHeight; i < imgHeight - initialDetectorHeight; ++i) {
      nv21Buffer.put(yPlaneBytes, i * yPlaneRowStride + initialDetectorWidth, width);
}

The solve is based on the fact that this function make a linear "buffer" with the image capture from camera drive. So, instead put the full image, I put only the sector of image wished.

This sector are selected by the additional paramenters looked in this solution. All of this paramentrs are given in the Dart abstraction, and put down between the calls of this lib until the QrDectector2. This solution don't work foor the the QrDetector1, used in older androids. Too, i not implemened it for IOs.

There is all the paramenters that I used for this, you need to pass it behind the call until QrCamera2 constructor:

        this.initialDetectorWidth = initialDetectorHeight;
        this.finalDetectorWidth = finalDetectorHeight;
        this.initialDetectorHeight = initialDetectorWidth;
        this.finalDetectorHeight = finalDetectorWidth;
        this.screenWidth = screenHeight;
        this.screenHeight = screenWidth;
        this.oldHeight = -1;
        this.oldWidth = -1;

and the preparation for the nv21Buffer for:

imgWidth = image.getWidth();
            imgHeight = image.getHeight();

            if (imgWidth != oldWidth && imgHeight != oldHeight) {
                oldWidth = imgWidth;
                oldHeight = imgHeight;

                widthRatio = (new Double(imgWidth)) / (new Double(screenWidth));
                heightRatio = (new Double(imgHeight)) / (new Double(screenHeight));

                initialDetectorWidth = (int) ((new Double(initialDetectorWidth)) * widthRatio);
                finalDetectorWidth = (int) ((new Double(finalDetectorWidth)) * widthRatio);
                if (finalDetectorWidth - initialDetectorWidth > imgWidth || finalDetectorWidth > imgWidth || initialDetectorWidth < 0) {
                    initialDetectorWidth = 0;
                    finalDetectorWidth = imgWidth;
                }
                width = finalDetectorWidth - initialDetectorWidth;

                initialDetectorHeight = (int) ((new Double(initialDetectorHeight)) * heightRatio);
                finalDetectorHeight = (int) ((new Double(finalDetectorHeight)) * heightRatio);
                if (finalDetectorHeight - initialDetectorHeight > imgHeight || finalDetectorHeight > imgHeight || initialDetectorHeight < 0) {
                    initialDetectorHeight = 0;
                    finalDetectorHeight = imgHeight;
                }
                height = finalDetectorHeight - initialDetectorHeight;
            }

This is put in copyImage method.
