### ISSUE TITLE
 Getter not found: 'detached'.

### ISSUE THREAD

**Issue by NithinPrabhu24** [rmtmckenzie/flutter_qr_mobile_vision#109]
App is not building for android please find the below error message 

Compiler message:
/C:/Users/nitin/flutter/.pub-cache/hosted/pub.dartlang.org/native_device_orientation-0.3.0/lib/native_device_orientation.dart:149:30: Error: Getter not found: 'detached'.
      case AppLifecycleState.detached:
                             ^^^^^^^^
Compiler failed on E:\NewFloder\flutter_app45\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm'.
> Process 'command 'C:\Users\nitin\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by yongjhih** [comment]
Seems like the AppAppLifecycleState.suspending renamed to AppLifecycleState.detached during upgraded to
flutter#v1.12.13+hotfix.5 from flutter#v1.9.1+hotfix.6 in stable channel.
native_device_orientation dependency has to be fixed for that.

**Comment by yongjhih** [comment]
Seems like the AppAppLifecycleState.suspending renamed to AppLifecycleState.detached during upgraded to
flutter#v1.12.13+hotfix.5 from flutter#v1.9.1+hotfix.6 in stable channel.
native_device_orientation dependency has to be fixed for that. https://github.com/rmtmckenzie/flutter_native_device_orientation/issues/16

**Comment by rmtmckenzie** [comment]
Should be resolved in the newest release. Let me know if it isn't.
