### ISSUE TITLE
Publish as flutter package

### ISSUE THREAD

**Issue by csutorasr** [rmtmckenzie/flutter_qr_mobile_vision#11]
I think this package should be published, if @rmtmckenzie has no doubt about it. [Here](https://flutter.io/developing-packages/) is some example how to do it.

**Comment by rmtmckenzie** [comment]
I plan on this as well once I get time =)

**Comment by rmtmckenzie** [comment]
I've published it now, it should show up once it has been approved: https://pub.dartlang.org/packages/qr_mobile_vision
