### ISSUE TITLE
Android camera image is wrong

### ISSUE THREAD

**Issue by jaumard** [rmtmckenzie/flutter_qr_mobile_vision#12]
Hello,
Thanks for this plugin! It's the only one who is really embedded into a flutter app and not just call for external screen and wait for the answer ^^ 

Unfortunately it's not working for me, I test on Android (Mi Mix 2 with Android 8.0.0), here is what I have (portrait and landscape which is even worse as when you move it didn't go the correct way)

![device-2018-05-20-172048](https://user-images.githubusercontent.com/2970449/40280395-c6109ff0-5c52-11e8-83e5-47be94a82f03.png)
![device-2018-05-20-172023](https://user-images.githubusercontent.com/2970449/40280396-c63412f0-5c52-11e8-8e1c-bab4574a1699.png)

And this is a native barcode scanner I have on my phone
![device-2018-05-20-172121](https://user-images.githubusercontent.com/2970449/40280397-c856feda-5c52-11e8-8dc1-075163145780.png)

Any idea what could be wrong ?

**Comment by rmtmckenzie** [comment]
Yeah the scaling is off on Android. I've been working on a fix but it's taking a while as I've run into orientation stuff and I haven't had much time the last couple of weeks. I'll be trying to get to it this week but no promises.

**Comment by jaumard** [comment]
My phone was the Xiaomi Mi Mix 2, and yes it has 2 cameras :) might be related too

**Comment by rmtmckenzie** [comment]
@jaumard  Can you test this with the newest version and reopen if it's still an issue?

**Comment by jaumard** [comment]
Sorry for the delay :) it works great now ! Thanks !
