### ISSUE TITLE
Camera preview upside down on Android

### ISSUE THREAD

**Issue by booooza** [rmtmckenzie/flutter_qr_mobile_vision#124]
**Description**: Since the upgrade to version 1.0.0+3 the camera preview on Android is rendered upside down (see screenshot). 

**Affected versions**: 1.0.0+3
**Affected devices**: Nexus 5X API 28 x86 (Emulator), Huawei P20 (Physical)
**Notes**:
- Tested in debug and release mode
- Tested with the provided example app
- Does not happen on iOS (iPhone 6)

![Screenshot_1586709459](https://user-images.githubusercontent.com/18515653/79074452-cce66a00-7cec-11ea-99ae-91ea481becc9.png)

Btw: thanks for the work towards 1.0.0! :-)

**Comment by GyuriMajercsik** [comment]
Yes, it's happening for me too.

**Comment by rmtmckenzie** [comment]
Okay so this was seen on a Huawei P20, @GyuriMajercsik which device did you see it on? 
I've tested this out on all the devices I have, so I assume it must be something to do with how the camera is reporting its orientation. I'll try to put out a version that spits out enough diagnostic info that I can figure out what's going on and attempt to fix it for you when I get a chance - probably not today but hopefully this week.

**Comment by booooza** [comment]
@rmtmckenzie alright, let me know if I can help with the debugging. Maybe you can reproduce it in an emulator, I also see it there (Nexus 5X API 28 x86).

**Comment by rmtmckenzie** [comment]
I actually didn't realize that you could use the camera in the emulator haha, I've managed to get it working for me now so I'm working on this. I think the main issue is that some Nexus 5x devices report weird things for the camera orientation, and that's been my primary test device.

**Comment by lucasbaizer2** [comment]
I have this same issue happening on my Pixel 1 (the hardware device, not an emulator), so I believe this is happening to more devices than the Nexus.

**Comment by subinsv** [comment]
I have this same issue on
Device: Redmi k20 pro
Android 10

**Comment by hoctq** [comment]
I have same issue on my Sony XZ1, android 10

**Comment by Pikaju** [comment]
Same issue on a Huawei P20 lite, Android 9

**Comment by rmtmckenzie** [comment]
Thanks for all the feedback everyone - I think that it's happening on most android devices right now. I've come up with a slightly hacky fix - basically ignoring devices that report a landscape right camera, because it appears that even though the camera reports the sensor as being rotated right, the image that comes out is still rotated left. Unfortunately that seems to have caused a discrepancy with iOS, so I'm still working on that, but I should have a fix out tomorrow hopefully.

**Comment by adriancsbna** [comment]
Same issue on Motorola Moto G5 Plus Android 8.1

**Comment by rmtmckenzie** [comment]
This should be fixed as of 1.0.1. Let me know if anyone is seeing any issues with that release!
