### ISSUE TITLE
App crashes on iOS after opening/closing QrCamera multiple times

### ISSUE THREAD

**Issue by booooza** [rmtmckenzie/flutter_qr_mobile_vision#126]
**Description**: App crashes badly on iOS after opening/closing QrCamera multiple times. Flutter does not report any logs as the app just terminates, probably because of a memory leak? The crash report shows `[vm-pageshortage]: The process was killed due to memory pressure`.

**Affected versions**: 1.0.1+1
**Affected devices**: iPhone 6 (Physical)
**Notes**:
- Tested in debug and release mode
- Tested with the provided example app
- Does not happen on Android

<img width="762" alt="memory" src="https://user-images.githubusercontent.com/18515653/79923615-30337300-8436-11ea-8195-ddd45125026d.png">

![flutter_qr_mobile_vision-iphone6-crash](https://user-images.githubusercontent.com/18515653/79919910-8cdf5f80-842f-11ea-9fa5-aebcab9966da.gif)

**Comment by rmtmckenzie** [comment]
yeah unfortunately this is an issue with the iOS implementation the GLTexture that shows the view. See this issue: https://github.com/flutter/flutter/issues/29586

It looks like the metal integration into flutter either just happened, or is happening very soon, at which point this could theoretically disappear. See https://github.com/flutter/flutter/issues/18208. Once that has for sure been integrated I'll try to test this again to see if it has gone away.

**Comment by booooza** [comment]
@rmtmckenzie argh, sounds bad.. actually what confused me was that this did not happen when testing the ios native barcode scanning from PR #94. Check out the memory graph there while doing the same thing:
<img width="757" alt="memory-native" src="https://user-images.githubusercontent.com/18515653/79961435-035b7c00-8487-11ea-9dba-5b394d806e00.png">

**Comment by rmtmckenzie** [comment]
hmmm, that's certainly quite interesting, as the issue I linked to was definitely just to do with the camera preview - I was reproducing it without having firebase included at all, although including it as well certainly exacerbated the problem.

It think it's time for me to re-test this when I get a chance - it's entirely possible that the IOSurface issue has been resolved and that it's now a memory leak either in firebase or my implementation that's causing the issue. Thanks for the rigorous testing =).

**Comment by booooza** [comment]
@rmtmckenzie you already had a chance to look into this? It seems like the objects filling up the memory are related to CoreMedia / IOSurface. These are the leftovers objects after every start/stop but the leak detection in Xcode was not able to identify them as a leak.

<img width="1024" alt="Bildschirmfoto 2020-05-10 um 13 36 25" src="https://user-images.githubusercontent.com/18515653/81502097-2b970780-92dc-11ea-8bdb-aa366497e058.png">

<img width="398" alt="Bildschirmfoto 2020-05-10 um 13 33 12" src="https://user-images.githubusercontent.com/18515653/81502103-32257f00-92dc-11ea-90fa-5248f5479ddd.png">

If I leave away textureHandler.setImageBuffer() I don't get the memory growth but QR detection still works so it's probably related to the buffering of the camera preview.
