### ISSUE TITLE
FIRAnalyticsVersionMismatch: Version does not match with Google App Measurement

### ISSUE THREAD

**Issue by vonqo** [rmtmckenzie/flutter_qr_mobile_vision#131]
`flutter_qr_mobile_vision` conflicting with `flutterfire` plugins. App crashing on start. 
I am using `firebase_messaging 6.0.13`.

**Exception message:**
`
*** Terminating app due to uncaught exception 'FIRAnalyticsVersionMismatch', reason: 'Google Analytics for Firebase version (50300000) does not match with Google App Measurement (50801000) version. Please update.'
`

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.4 18E2034, locale en-MN)
    • Flutter version 1.12.13+hotfix.9 at /Users/von/Development/flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/von/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4
```

**Comment by rmtmckenzie** [comment]
I don't require any particular version of any of the firebase libraries, so that'll be down to the dependencies that FirebaseMobileVision is pulling in. You can specify specific versions in your Podfile if you need to - I don't want to tie anything to a particular version because it could break it for many other people.

**Comment by rmtmckenzie** [comment]
Also, see #129 for some steps to make sure everything in cocoapods is up to date.
