### ISSUE TITLE
Does it detects 2D barcodes also? 

### ISSUE THREAD

**Issue by anwesh408** [rmtmckenzie/flutter_qr_mobile_vision#138]
I have tried with the example mentioned in the repo, it detects the QR codes but does it also detects 2d bar codes ?
it looks like it doesnt. if not, could you please include the support for barcodes as well ?

**Comment by rmtmckenzie** [comment]
It should support all the types of barcodes that FirebaseMobileVision does:
```
Linear formats: Codabar, Code 39, Code 93, Code 128, EAN-8, EAN-13, ITF, UPC-A, UPC-E
2D formats: Aztec, Data Matrix, PDF417, QR Code
```

If it doesn't work for a particular format, could you post the code you're trying to scan along with its type? It might also be worth specifying just that type in `formats` to see if it works better then.

**Comment by anwesh408** [comment]
ok Thanks.
