### ISSUE TITLE
Crash on ios - com.apple.avfoundation.videodataoutput.bufferqueue

### ISSUE THREAD

**Issue by dagba** [rmtmckenzie/flutter_qr_mobile_vision#145]
com.apple.avfoundation.videodataoutput.bufferqueue
EXC_BREAKPOINT 0x0000000100a9df0c

QrReader.swift - line 183
specialized QrReader.captureOutput(_:didOutput:from:) + 183

**Comment by pynner** [comment]
Any luck debugging this one?
