### ISSUE TITLE
Request download for engine barcode "loop"

### ISSUE THREAD

**Issue by GregorySech** [rmtmckenzie/flutter_qr_mobile_vision#15]
I've cloned the git repo, and started the example on Android. 
Pressed the FAB, given permissions and seen the camera widget animate however no QRCode can be scanned.
In the terminal I get the following warnings and infos:

> W/DynamiteModule( 4967): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 4967): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
I/DynamiteModule( 4967): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702
W/System  ( 4967): ClassLoader referenced unknown path: 
W/System  ( 4967): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000067/n/arm64-v8a
I/Vision  ( 4967): Loading library libbarhopper.so
I/Vision  ( 4967): libbarhopper.so library load status: false
I/Vision  ( 4967): Request download for engine barcode
I/SendBroadcastPermission( 4967): action:null, mPermissionType:0
W/BarcodeNativeHandle( 4967): Native handle not yet available. Reverting to no-op handle.
I/CameraManagerGlobal( 4967): Connecting to camera service
W/DynamiteModule( 4967): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 4967): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
I/DynamiteModule( 4967): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702

Especially these five lines keep looping:
> I/Vision  ( 4967): Loading library libbarhopper.so
I/Vision  ( 4967): libbarhopper.so library load status: false
W/DynamiteModule( 4967): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 4967): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
I/DynamiteModule( 4967): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702

From what I've understood something went wrong in the download of the vision model necessary for this package to run.
Is there some way to monitor the downloading of said module or to have some way to intercept this issue on Flutter to behave differently from a camera that will never detect a QRCode?
Also anyone knows how to fix this? If needed I'll post this point on StackOverflow.

**Comment by GregorySech** [comment]
![qrcode](https://user-images.githubusercontent.com/13541001/42345992-698499bc-80a1-11e8-83a3-eeeca2f96107.jpg)
This is the application running, it simply doesn't detect any QRCode.

**Comment by rmtmckenzie** [comment]
I'm not 100% sure why that would be. Could you give me some more details i.e. which version of android, what device, etc.

Another thing to check is that your play services are relatively up to date - the Google Mobile Vision library uses the play services to do various things.

**Comment by rmtmckenzie** [comment]
Also, try explicitly requiring a particular version of play services and play services base in your app/build.gradle file. That may help. 

i.e.
```
dependencies { 
  ....
    implementation 'com.google.android.gms:play-services-vision:15.0.2'
    implementation 'com.google.android.gms:play-services-base:15.0.1'
  ....
}
```

I should probably update the plugin to require the newest version or at least be more transitive, but this should help....

**Comment by GregorySech** [comment]
I'll try later today. I tried it on a Huawei p10 lite with Android 7.0,
google play services version: 12.6.85 which is up to date according to (Italy's) Play Store.

As soon as I try that particular version of the play services I'll update the thread.

**Comment by rmtmckenzie** [comment]
I've also just published a new version that updates the dependency to the most recent version.

**Comment by GregorySech** [comment]
Ok sorry for the delay, I've tried version 0.0.2 of the package and it doesn't loops anymore on the console however it still doesn't detect any QRCode. I've also tried adding the dependencies directly into the app's build.gradle but nothing changed.

**Comment by rmtmckenzie** [comment]
Weird - it doesn't spit out any errors? Have you tried reading any other types of barcodes?

**Comment by rmtmckenzie** [comment]
I'm going to close this as it's pretty old now. If you're still using the plugin, please test it with the most recent version and reopen this is you're still seeing issues.

**Comment by rostopira** [comment]
I have the same issue with OnePlus 5T on Android 9 and 0.3.1 plugin
Tried to manually change version of vision dependency to 19.0.0, didn't help
