### ISSUE TITLE
No turn flashlight on and off

### ISSUE THREAD

**Issue by RafatMeraz** [rmtmckenzie/flutter_qr_mobile_vision#153]
When you guys gonna fix this issue! This package is awesome, but this flashlight issue really painful.

**Comment by rmtmckenzie** [comment]
I'm half way through a refactor that would fix that along with a bunch of the other issues but I honestly just haven't had time to work on it for a very long time. I do still want to get that out there but I also really don't know when I'll have time again.

**Comment by RafatMeraz** [comment]
Thanks for getting back to me. I hope you will complete it soon sir.

**Comment by david-adewoyin** [comment]
are you still planning on adding the flashlight , it will be a great help. Anyway thanks for the plugin is very nice and easy to use
