### ISSUE TITLE
QrCameraC1.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by jeancarlos2020** [rmtmckenzie/flutter_qr_mobile_vision#154]
![image](https://user-images.githubusercontent.com/6289980/96171210-389ecf00-0eea-11eb-881f-727bf5457233.png)

**Comment by rmtmckenzie** [comment]
This has been reported previously. QrCameraC1 user a deprecated API... because it needs to use the Camera V1 deprecated API. It isn't used on devices that support the newer CameraV2 api.
