### ISSUE TITLE
Minimum SDK preventing Gradle build

### ISSUE THREAD

**Issue by jameshmread** [rmtmckenzie/flutter_qr_mobile_vision#16]
Hello, just installed this package but I cannot run it due to the error detailed below....

I have tried adding this to the androidmanifest.xml which does not help

    <uses-sdk android:minSdkVersion="21"/>

Hope you can help :)

Launching lib\main.dart on ONEPLUS A3003 in debug mode...
C:\{pathToApp}/app\android\app\src\main\AndroidManifest.xml:12:5-14:62 Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:qr_mobile_vision] C:\{pathToApp}\app\build\qr_mobile_vision\intermediates\manifests\full\debug\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 17,
		or use tools:overrideLibrary="com.github.rmtmckenzie.qrmobilevision" to force usage (may lead to runtime failures)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:qr_mobile_vision] C:\{pathToApp}\app\build\qr_mobile_vision\intermediates\manifests\full\debug\AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 17,
  		or use tools:overrideLibrary="com.github.rmtmckenzie.qrmobilevision" to force usage (may lead to runtime failures)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 3s
Gradle build failed: 1

**Comment by wimombelets** [comment]
This is a reproducible exception but can be remedied.
Instead of adding the `<uses-sdk>` element to the android manifest file you can set the android defaultConfig minSdkVersion to 17 in the android/app/build.gradle file.

**Comment by rmtmckenzie** [comment]
@jameshmread did the suggestion provided by @wimombelets help you out?

**Comment by jaumard** [comment]
One question about the minSDK mine was 16 but with this module I had to put 17, any reason you choose 17 and not 16 @rmtmckenzie ?

**Comment by rmtmckenzie** [comment]
Uh no particular reason I don't think other than that's what my project was targeting and that's the earliest device I have to test with. I'll be pushing a new update out soon and I'll lower it to 16.

**Comment by rmtmckenzie** [comment]
Okay version 0.0.3 has had the min lowered to 16. I haven't tested it at all on 16 so there's a chance it might not work at all.

**Comment by rmtmckenzie** [comment]
ah. nvm, looking at the code a bit more (should have done that before pushing a new version) I may have a min of API 19.  Just checking to see if there's an actual reason for that =D

**Comment by jaumard** [comment]
Thanks @wimombelets ! Will check that tomorrow on my side :)

**Comment by rmtmckenzie** [comment]
This should be fixed so I'm going to close it; if anyone has an issue please re-open or create a new issue =).

**Comment by jaumard** [comment]
Sorry I didn't get feedback :) all good for API 16, I was able to install it be not test the scan as my shity device didn't have enough memory :( too old...
