### ISSUE TITLE
Switching camera

### ISSUE THREAD

**Issue by fabmatz** [rmtmckenzie/flutter_qr_mobile_vision#166]
Hello,
I like your plugin a lot, because it is fast and scans continuously. Is there a way to switch to the front camera? I couldn't find a way how to switch at your plugin.

Greetings and you do a really good job!
Fabian

**Comment by maganap** [comment]
@fabmatz I need to use the front camera as well. Did you find a solution or any other plugin that helps? Thanks in advance

**Comment by fabmatz** [comment]
@maganap I made my one durty fix. After downloading the package, i changed the package code. I only needed for Android and after a view tries i figured out, that a change in file "QrCameraC2.java" helped me. It path is "C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-2.0.0\android\src\main\java\com\github\rmtmckenzie\qrmobilevision".
Probably depending on your need you have to try this or some of the others files. Also if you need it for iOS you need to find the other files for that.

**Comment by maganap** [comment]
@rmtmckenzie I see it's now a configurable property. Awesome, thanks!

**Comment by rmtmckenzie** [comment]
oh whoops thanks, I'll fix that
