### ISSUE TITLE
How to Load QR from file?

### ISSUE THREAD

**Issue by prateekmedia** [rmtmckenzie/flutter_qr_mobile_vision#167]

**Comment by prateekmedia** [comment]
@rmtmckenzie Any reason why you closed this, the title was enough to describe the problem?

**Comment by prateekmedia** [comment]
@rmtmckenzie I asked it here cause their isn't any other place to ask this and also the method to do this is not in the readme.

**Comment by rmtmckenzie** [comment]
That's one reason. You need to provide way more details for this to be a useful query. I can't tell what you're asking; are you wanting to read the data out of a qr code that's in an image file? And if you're wanting to, that depends on a lot of things like the format of the image file, whether it's from the native system or something you're loading from a URL. 

The second reason is that if you are asking something along the lines of what I described above, that would be outside the scope of this library (which admittedly you wouldn't necessarily know, but one of the first lines of the readme says "This plugin uses Android & iOS native APIs for reading images from the device's camera").  I have enough feature requests already that I don't have for which are directly related to what the plugin is meant for - and the primary purpose for this library is to allow people to add a qr scanner that just works in as simple a way as possible.

If you're wanting to use the firebase mobile vision library in any way other than what this plugin does directly with the camera, you'll probably have better luck using the plugin that google provides for the firebase_ml_vision library: https://pub.dev/packages/firebase_ml_vision
