### ISSUE TITLE
NNBD Null safety support

### ISSUE THREAD

**Issue by DevNico** [rmtmckenzie/flutter_qr_mobile_vision#169]
Flutter 2.0 is out and with it comes stable null safety support. This is one of the last packages we depend on that doesn't have a null safe version, blocking use from migrating. Is work on null safety already in progress? If not here is the migration guide https://dart.dev/null-safety/migration-guide. Would be awesome to have a null safe release of this (btw awesome) package soon!

**Comment by rmtmckenzie** [comment]
I do _intend_ to do it soon, but whether I get time is another question - I've not had any in quite a while to invest into this package.

**Comment by rmtmckenzie** [comment]
Closed by #171
