### ISSUE TITLE
iOS 9

### ISSUE THREAD

**Issue by mathd** [rmtmckenzie/flutter_qr_mobile_vision#17]
Hello,

My application work really well under iOS 11  but I have some issue under iOS 9 (9.3.5 last version for iPod gen 5)

This is the error message I get:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building FutureBuilder<PreviewDetails>(dirty, state:
flutter: _FutureBuilderState<PreviewDetails>#6fc05):
flutter: 'package:qr_mobile_vision/qr_camera.dart': Failed assertion: line 115 pos 16: 'previewDetails !=
flutter: null': is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Preview (package:qr_mobile_vision/qr_camera.dart)
flutter: #3      QrCameraState.build.<anonymous closure>.<anonymous closure> (package:qr_mobile_vision/qr_camera.dart:74:32)
flutter: #4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
flutter: #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730:27)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642:15)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242:33)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #14     _invoke (dart:ui/hooks.dart:120:13)
flutter: #15     _drawFrame (dart:ui/hooks.dart:109:3)
flutter: (elided 2 frames from class _AssertionError)
```

**Comment by rmtmckenzie** [comment]
hmm I haven't tested against iOS 9. I'm not actually sure I can downgrade my test phone to 9!  But this seems to be completely within the realm of flutter. Could you include a log from the iOS side of things to see if something else is going on?

Also, it would be helpful if you could try debugging through the code to see what happens - in qr_camera, check that 'asyncInitOnce' is getting a previewDetails that isn't null; and if it is null check in QrMobileVision.start that it gets to the end of the function.

I can't see any way that it doesn't unless it has an error, but that should result in a throw earlier on... 

I probably won't have time to test this for a couple of days at least, so your help with debugging the issue would be appreciated =).

**Comment by mathd** [comment]
The error come in the build method of the widget. 
Here is the content of the details variable:
AsyncSnapshot<PreviewDetails>(ConnectionState.done, null, PlatformException(Error 2, qr_mobile_vision, iOS Versions before 10 not supported.)

So my guess is that you are using API not available under iOS 8 or 9.

**Comment by mathd** [comment]
In the file: https://github.com/rmtmckenzie/flutter_qr_mobile_vision/blob/master/ios/Classes/QrMobileVisionPlugin.m line 238, there is a version check for iOS 10.0. I can't see anywhere in the Mobile Vision API documentation why this would not work for iOS before 10.0.

**Comment by rmtmckenzie** [comment]
I remember now - there's a new api for getting an AVCaptureDevice in 10.0, so I just used it. I was planning on eventually going back and doing it for < 10.0, but never got around to it.

**Comment by mathd** [comment]
I've created a pull request to fix iOS9. The documentation says that if should work from iOS4 to iOS9. But I've only tested it on iOS 9.3.5 and iOS 11.4.

**Comment by mathd** [comment]
This work well now (but slow), thank you.

**Comment by rmtmckenzie** [comment]
Hmm. I just realized that I haven't exposed the method to choose which types of barcodes/qr codes to scan through the QrCamera widget - I'll add that in when I get a chance. Specifying the exact type should speed up the processing somewhat. On my iPhone it doesn't really slow it down but I could see lower-spec'd hardware having more trouble.
