### ISSUE TITLE
on IOS, format is ignored

### ISSUE THREAD

**Issue by luismarcilio** [rmtmckenzie/flutter_qr_mobile_vision#178]
Hello. Thank you for the package, in first place.

I noticed that it does not pass the format parameter to IOS barcode scanner, [here](https://github.com/rmtmckenzie/flutter_qr_mobile_vision/blob/master/ios/Classes/QrReader.swift#L124)

It would be much appreciated if you could fix that in a future release.

Thanks.

**Comment by Naweap** [comment]
@luismarcilio Did you find any workaround about that ?

**Comment by luismarcilio** [comment]
> @luismarcilio Did you find any workaround about that ?

No. I forked the code and forced the format I needed and used it from my fork.
You can have a look at it here:

https://github.com/luismarcilio/flutter_qr_mobile_vision/blob/385a9f77a6404174e9903a84efc7d72a32b99bf8/ios/Classes/QrReader.swift#L124

**Comment by Naweap** [comment]
@luismarcilio First thanks for your quick answer.

Do you think there could be any way to use the provided formats list. For exemple using the options parameter ?

I use many formats in my app and it's mandatory for me.

**Comment by luismarcilio** [comment]
> @luismarcilio First thanks for your quick answer.
> 
> Do you think there could be any way to use the provided formats list. For exemple using the options parameter ?
> 
> I use many formats in my app and it's mandatory for me.

You can try to fix it. Check the java code in android directory. It seems well written. 
You can get more information in Google's documentation: https://developers.google.com/ml-kit/reference/swift/mlkitbarcodescanning/api/reference/Classes/BarcodeScanner
If you fix it, you could contribute and do a pull request to package.

**Comment by rmtmckenzie** [comment]
Hey guys! Sorry, I really haven't had any time to work on this plugin for a while, but if you do a PR I'll merge it ASAP. Otherwise if you can wait until November I'm going to have a lot more time then so I should be able to get to things like this!

**Comment by ryanduffyegov** [comment]
I also have a need for this to work in both iOS and Android.  I am willing to help test the fix if some one has this working.

**Comment by MatheusLimaN** [comment]
> Hey guys! Sorry, I really haven't had any time to work on this plugin for a while, but if you do a PR I'll merge it ASAP. Otherwise if you can wait until November I'm going to have a lot more time then so I should be able to get to things like this!

Hello, I did a PR to solve this issue, it worked for me, I hope it helps. (https://github.com/rmtmckenzie/flutter_qr_mobile_vision/pull/188)

Tested on iPhone XR
