### ISSUE TITLE
Conflict with firebase_core

### ISSUE THREAD

**Issue by yarrumretep** [rmtmckenzie/flutter_qr_mobile_vision#18]
It seems there is some kind of transitive dependency collision between the qr_mobile_vision plugin and the firebase_core plugin on Android.  When both are present in a flutter project, and the camera is activated, the app crashes with:

```
ejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.zzdkv>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbgl;
I/ple.alephwalle(25631):   at void com.github.rmtmckenzie.qrmobilevision.QrDetector.<init>(com.github.rmtmckenzie.qrmobilevision.QRReaderCallbacks, android.content.Context, int) (QrDetector.java:32)
I/ple.alephwalle(25631):   at void com.github.rmtmckenzie.qrmobilevision.QRReader.<init>(int, int, android.content.Context, int, com.github.rmtmckenzie.qrmobilevision.QRReader$QRReaderStartedCallback, com.github.rmtmckenzie.qrmobilevision.QRReaderCallbacks, android.graphics.SurfaceTexture) (QRReader.java:44)
```

Recipe: add the following dependency to the example project:

```
dependencies:
  firebase_core: "^0.2.4"
  flutter:
    sdk: flutter
```

Push the button and crash.

It feels maybe like an obfuscated class reference collision between versions of a jar file somewhere in the dependency tree for the google play services...?

**Comment by yarrumretep** [comment]
Fix appears to be to bump the version to `com.google.android.gms:play-services-vision:15.0.1`.

I'll submit a PR

**Comment by rmtmckenzie** [comment]
Thanks, I'd been meaning to do this but I've had a crazy few weeks at work. It seems to stem from having different versions of play-services-vision and play-services-base - in my app, I've worked around it by simply specifying both of them in my build.gradle. Not ideal though so thanks =D.
