### ISSUE TITLE
[CR] native_device_orientation has a newer version (Flutter 3.0 w. support)

### ISSUE THREAD

**Issue by MathiasCochet** [rmtmckenzie/flutter_qr_mobile_vision#196]
https://github.com/rmtmckenzie/flutter_qr_mobile_vision/blob/master/pubspec.yaml

update native_device_orientation version 1.1.0 -> 1.1.2

**Comment by rmtmckenzie** [comment]
I'm aware, I wrote that plugin too =D. I've published a beta version of this plugin (4.0.0-dev.1) as there's a few things I'm still not 100% sure work in the new version, so if you're brave you could try it out (I did test on my usual Pixel3a/Nexus4/iPhone7 test devices though and things seem to be working).
