### ISSUE TITLE
Look into implementing with ML Kit instead (deprecation)

### ISSUE THREAD

**Issue by jaumard** [rmtmckenzie/flutter_qr_mobile_vision#20]
Just read this on the mobile vision website, just wanted to know if you already using ML Kit here or plan to do it as they say they will stop the API at some point

Thanks

**Comment by rmtmckenzie** [comment]
Didn't know that. I'll update to MLKit when I get a chance - I need this for my project so if it stops working that would be less than ideal =D. Thanks!

**Comment by jaumard** [comment]
:) I need it also, that's why I checking everything to see if it safe to use or not ^^ might be able to help on some issues too if needed

**Comment by rmtmckenzie** [comment]
So I looked into this a bit more. It would make the implementation a bit easier, but unfortunately necessitates both including the core firebase libraries and more importantly signing the app up for a firebase account. 

As much as using the updated library would probably be a good idea, and I'm guessing quite a few people use firebase for other reasons anyways, switching means that a good percentage of the people using this plugin might have to do some work and/or re-evaluate whether they want to use it at all.

If the mobile vision library stops working I'll definitely switch to using the firebase version. But until then (or at least until it's announced) I'll keep using the current library as it means less friction for developers.

I'll leave this open but won't do any work on it until I hear something about the mobile vision API.

**Comment by red42** [comment]
Just as a small addition to this conversation: I've specifically tested the QR code reading capabilities of both libraries, and unfortunately, ML Kit / ML Vision (as of early 2019) still performs much worse than Google Mobile Vision, especially in "real life" conditions, with faded or distorted QR codes.

My project uses Firebase, but does not use ML Kit for this reason.

**Comment by nhwilly** [comment]
Ditto here, @red42

**Comment by rmtmckenzie** [comment]
1.0.0 now supports this (although I almost feel silly for commenting on an issue this old >_<).
