### ISSUE TITLE
camera freezes on IOS when flash is turned on or when toggleFlash() is called. 

### ISSUE THREAD

**Issue by Hemant-sha** [rmtmckenzie/flutter_qr_mobile_vision#222]
Works fine on Android but the camera freezes on IOS

**Comment by Hemant-sha** [comment]
Works fine on Android but the camera freezes on IOS

**Comment by lovelessX** [comment]
I also have this but only on some models. iPhone 13 Mini and iPhone SE2, it works fine. On iPhone 14 Pro with iOS 17, it happens.

**Comment by lovelessX** [comment]
The issue is due to the default video camera device not being the same as the device being used on the three-camera high-end iPhones. The lamp needs to trigger off of the same device.
