### ISSUE TITLE
Conflict with Firebase

### ISSUE THREAD

**Issue by TercyoStorck** [rmtmckenzie/flutter_qr_mobile_vision#235]
I'm trying to add firebase analytics in my project that uses qr_mobile_vision. But I'm facing this error when build for iOS (or run pod install).

I've tried pod repo update and pod install --repo-update also. But get the same error over and over.

```[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In snapshot (Podfile.lock):
    GoogleUtilities/UserDefaults (= 8.0.2, ~> 8.0)

  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 11.3.0, which depends on
      Firebase/Analytics (= 11.0.0) was resolved to 11.0.0, which depends on
        Firebase/Core (= 11.0.0) was resolved to 11.0.0, which depends on
          FirebaseAnalytics (~> 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseInstallations (~> 11.0) was resolved to 11.1.0, which depends on
              GoogleUtilities/UserDefaults (~> 8.0)

    qr_mobile_vision (from `.symlinks/plugins/qr_mobile_vision/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning was resolved to 0.60.0, which depends on
        GoogleMLKit/MLKitCore (= 0.60.0) was resolved to 0.60.0, which depends on
          MLKitCommon (~> 0.60.0) was resolved to 0.60.0, which depends on
            GoogleUtilities/UserDefaults (~> 6.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `GoogleUtilities/UserDefaults` inside your development pod `qr_mobile_vision`.
   You should run `pod update GoogleUtilities/UserDefaults` to apply changes you've made.```

**Comment by rmtmckenzie** [comment]
The version you're using appears to be quite old. This plugin doesn't specify which version of the barcode scanning library to use, that's all up to the app. 

Have you tried updating GoogleMLKit/BarcodeScanning? 


That should be with:

```
pod update GoogleMLKit/BarcodeScanning
```
And it might not be a bad idea to run `pod update` for all pods. 

Or check your Podfile to make sure you didn't add a constraint.

**Comment by scopendo** [comment]
I had a similar issue except with `GoogleDataTransport` after updating from package `firebase_core` 3.2.0 to 3.4.1, after running:

```
$ flutter clean; flutter pub get
$ cd ios
$ rm Podfile.lock
$ rm -rf Pods
$ pod install --repo-update
```

I reverted to `firebase_core` 3.2.0 and it was fine again.

**Comment by mauriziopinotti** [comment]
> I had a similar issue except with `GoogleDataTransport` after updating from package `firebase_core` 3.2.0 to 3.4.1, after running:
> 
> ```
> $ flutter clean; flutter pub get
> $ cd ios
> $ rm Podfile.lock
> $ rm -rf Pods
> $ pod install --repo-update
> ```
> 
> I reverted to `firebase_core` 3.2.0 and it was fine again.

Reverting firebase works but that's not an acceptable solution: versions should go forwards, not backwards.
`qr_mobile_vision` plugin should update dependencies to use `GoogleMLKit/BarcodeScanning` 3.2.0 that uses `GoogleDataTransport` 10.x.

**Comment by rmtmckenzie** [comment]
I haven't worried about a minimum constraint as this plugin has been using the BarcodeScanning pod since it was first published by Google under that name (it was Firebase Mobile Vision before that), so any version should work so long as things like this don't come up. 

As to the firebase core issue, there's really not anything I can do about it as it is between the two teams at google. There is [an issue open on their bug tracker](https://issuetracker.google.com/issues/362452861), you can +1 it to hopefully prompt them to resolve this sooner.

**Comment by mauriziopinotti** [comment]
Looks like there's a new MLKitBarcodeScanning 6.0.0 that uses MLKitCommon 12.0.0 that uses GoogleDataTransport 10.0, so that should make it.

https://github.com/CocoaPods/Specs/blob/master/Specs/b/5/4/MLKitBarcodeScanning/6.0.0/MLKitBarcodeScanning.podspec.json
https://github.com/CocoaPods/Specs/blob/master/Specs/c/c/6/MLKitCommon/12.0.0/MLKitCommon.podspec.json

**Comment by lovelessX** [comment]
Yeah, they released the fix for https://issuetracker.google.com/issues/362452861, @rmtmckenzie. I'm still having a pod issue but maybe it's something on my side.

**Comment by lovelessX** [comment]
Note you now have to ensure your app's minimum iOS version is 15.5 to support the latest update from Google.

**Comment by mauriziopinotti** [comment]
I have pushed to fix this, while not merged you can temporarily override the dependency by using

```yaml
dependency_overrides:
  # Waiting for https://github.com/rmtmckenzie/flutter_qr_mobile_vision/pull/238
  qr_mobile_vision:
    git: https://github.com/easyhour/flutter_qr_mobile_vision.git
```

**Comment by lovelessX** [comment]
@rmtmckenzie As long as iOS apps target 15.5, I believe this issue can now be closed. Whether or not you want to enforce it with https://github.com/rmtmckenzie/flutter_qr_mobile_vision/pull/238 is up to you.

**Comment by rmtmckenzie** [comment]
I've updated the example and added something in the README about the iOS version. I'd rather not enforce a minimum version as it is still possible to use older versions of Firebase and the BarcodeScanner library if you need to target ios versions > 15.5.
