### ISSUE TITLE
App in background don't pause the camera

### ISSUE THREAD

**Issue by jaumard** [rmtmckenzie/flutter_qr_mobile_vision#25]
On my mi mix 2 if I tap the home button to leave the app in background, the camera still run and show on logs : 
```
I/RequestThread-0(28712): Producing jpeg buffer...
I/RequestThread-0(28712): Received jpeg.
I/RequestThread-0(28712): Producing jpeg buffer...
I/RequestThread-0(28712): Received jpeg.
I/RequestThread-0(28712): Producing jpeg buffer...
I/RequestThread-0(28712): Received jpeg.
I/RequestThread-0(28712): Producing jpeg buffer...
I/RequestThread-0(28712): Received jpeg.
I/RequestThread-0(28712): Producing jpeg buffer...
```

PS: would be also nice to don't have those output ^^ it pollute our logs and seing our log became complicate

**Comment by rmtmckenzie** [comment]
Hmm, thought I had logic in there to shut off when the app closed but apparently not. I can add it in. And while that logging is certainly associated with this plugin, I don't think I'm actually doing it....

**Comment by rmtmckenzie** [comment]
Pushed v0.0.5 that should fix this. Takes a while to process...

**Comment by jaumard** [comment]
Look like it stop it correctly now :) thanks !
