### ISSUE TITLE
Auto focus not working Samsung SM-G900F

### ISSUE THREAD

**Issue by jaumard** [rmtmckenzie/flutter_qr_mobile_vision#30]
Android 7.1.2.
Other app manage to auto focus and detect barcode when with this module image stay blurry. 
Nothing on logs except:
```
07-23 14:18:00.354 13857-13869/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-3] cancelBuffer: BufferQueue has been abandoned
07-23 14:18:02.186 13857-13870/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] dequeueBuffer: attempting to exceed the max dequeued buffer count (9)
07-23 14:18:03.396 13857-13869/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] cancelBuffer: BufferQueue has been abandoned
07-23 14:18:03.397 13857-13870/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] cancelBuffer: BufferQueue has been abandoned
07-23 14:18:03.398 13857-14153/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] cancelBuffer: BufferQueue has been abandoned
07-23 14:18:03.398 13857-13869/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] cancelBuffer: BufferQueue has been abandoned
07-23 14:18:03.399 13857-13870/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] cancelBuffer: BufferQueue has been abandoned
07-23 14:18:03.400 13857-14153/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] cancelBuffer: BufferQueue has been abandoned
07-23 14:18:03.401 13857-13869/com.kiwi.merchant.kiwimobile E/BufferQueueProducer: [SurfaceTexture-1-13857-5] cancelBuffer: BufferQueue has been abandoned
```

**Comment by rmtmckenzie** [comment]
I'm pushing a new version soon, try that or the master branch out. With the camera2 api I assumed autofocus was the default for all camera so didn't set it explicitly; I've added in a check whether it's supported and set the camera to autofocus if it is.

**Comment by jaumard** [comment]
No luck with last version, it still doesn't manage to focus (but I think he is trying) and doesn't read the barcode where a native camera can easily focus a detect the barcode :(

Also I notice that in this device camera is laggy where native is not, I also test the camera plugin of flutter and it doesn't lag too might worth taking a look at how they did to apply it here ?

**Comment by MikeSWelch** [comment]
I just wanted to add that I'm having this problem on multiple devices.  Most notably it happens on my SM G950U (Galaxy S8) very consistently.  I'm happy to help troubleshoot this problem in any way that I can.

**Comment by MikeSWelch** [comment]
Some extra info:  SM G920V (Galaxy S6) has this same problem.  Pixel 2 does not suffer from this problem and works flawlessly.

**Comment by rmtmckenzie** [comment]
I've changed the way that it does autofocus with the camera2 api. Could you test whether it works better now?

**Comment by allanwolski** [comment]
the focus is still a problem here.

**Comment by MikeSWelch** [comment]
I have the same problem with autofocus.

I found the solution is to comment out the following lines in QrCameraC2.java:

Lines 194 and 195:
```
//previewBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_AUTO);
                //previewBuilder.set(CaptureRequest.CONTROL_AF_TRIGGER, CaptureRequest.CONTROL_AF_TRIGGER_START);
```

I have tested this with the Galaxy S6, the Galaxy S8, and the Pixel 2.

**Comment by rmtmckenzie** [comment]
I think that's the old version of the app @MikeSWelch - I try to use continuous autofocus instead if it's available. Could you test whether that works better for you now with version 0.1.0? And @allanwolski which device are you seeing the problem on?

**Comment by MikeSWelch** [comment]
I was still using the git repo to pull your plugin.  I switched to qr_mobile_vision: "^0.1.0" and now everything is working fine, thanks so much for all your hard work!

**Comment by allanwolski** [comment]
I tested this with the Galaxy S5.

**Comment by MrNickBarker** [comment]
I had autofocus issues while testing on a Lexus Nexus 5X on Android 7.2.1.  I fixed it by replacing 
```
previewBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_AUTO);
previewBuilder.set(CaptureRequest.CONTROL_AF_TRIGGER, CaptureRequest.CONTROL_AF_TRIGGER_START);
```
with
```
previewBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_VIDEO);
```
or 
```
previewBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);
```

**Comment by rmtmckenzie** [comment]
A few people have reported that it is working for them now (and I've made a few subsequent changes). So I'm going to close this for now - please re-open it if you're still see the issue.
