### ISSUE TITLE
Dropping frames on Oneplus 6

### ISSUE THREAD

**Issue by mskrip** [rmtmckenzie/flutter_qr_mobile_vision#35]
Even with provided example app when the preview is opened the camera window stutters a lot and I get a lot of log like this regardless of what is camera looking at:

```
I/System.out(28650): Dropping frame
I/System.out(28650): Dropping frame
I/System.out(28650): Dropping frame
I/System.out(28650): Dropping frame
I/System.out(28650): Dropping frame
I/System.out(28650): Dropping frame
I/chatty  (28650): uid=10166(com.github.rmtmckenzie.qrmobilevisionexample) AsyncTask #1 identical 15 lines
```

**Comment by s-bauer** [comment]
Works fine for me on my OnePlus 6. Are you running in release mode?

**Comment by allanwolski** [comment]
Same thing here with a Galaxy S5 running in release mode.

**Comment by rmtmckenzie** [comment]
I've removed that particular log message. Frames do still get dropped from the processing queue, but it shouldn't tell you about it any more, and realistically the qr detection doesn't need to run every single frame to still seem pretty performant - it's more important that the preview looks smooth.
