### ISSUE TITLE
Remove "Dropping frame" output

### ISSUE THREAD

**Issue by s-bauer** [rmtmckenzie/flutter_qr_mobile_vision#36]
Could you remove the "Dropping frame" output from the Android implementation? It really messes up the flutter logs!

https://github.com/rmtmckenzie/flutter_qr_mobile_vision/blob/d1287beccce6e58c7129805a567141517e57098a/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrDetector.java#L77

**Comment by rmtmckenzie** [comment]
Sorry for the delay, I've been on holiday. I agree that's not the right thing to do there. Would a debug-level log statement still be annoying for you? That should be easier to filter out. I see some value in having a some sort of logging at least - without a log statement at least you'd never be able to know when it drops frames.

**Comment by s-bauer** [comment]
Hey there, I hope you had great holidays! How about adding a callback in dart, which gets fired when a frame drops? This enables developers to detect freezes, so they can react to it. Or at least add the ability to enable/disable debug statements. 

I might be able to take a look at this myself this weekend.

**Comment by rmtmckenzie** [comment]
In the newest version I've removed the debug statement completely. I should probably put something in at some point but enough people are annoyed by it that it doesn't seem important to keep it any more.
