### ISSUE TITLE
How can I stop the camera?

### ISSUE THREAD

**Issue by Hayarobee** [rmtmckenzie/flutter_qr_mobile_vision#40]
Thanks for the useful widget.
Would you tell me how can I stop the camera?
I try to change other widgets, then throw the exception.

I/flutter (18772): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3436 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

Is there any stop method or something like that?

**Comment by rmtmckenzie** [comment]
Hmm. It's weird that's happening - what exactly are you doing when it throws that error? Pushing a new screen on top?  When the widget is disposed it should be stopping automatically.

If you could attach the full stacktrace that could be helpful as well.

That being said, there is an explicit stop method for the QrCameraState. You'll have to use a GlobalKey to get a reference to it which is a bit hacky, but I haven't got around to making a better solution.

**Comment by Hayarobee** [comment]
I use a TabView widget.
Unfortunately, now I am working a different part, 
so if I will find the same problem again then let you know.
thanks.

**Comment by normancarcamo** [comment]
> Hmm. It's weird that's happening - what exactly are you doing when it throws that error? Pushing a new screen on top? When the widget is disposed it should be stopping automatically.
> 
> If you could attach the full stacktrace/log that could be helpful as well.
> 
> That being said, there is an explicit stop method for the QrCameraState. You'll have to use a GlobalKey to get a reference to it which is a bit hacky, but I haven't got around to making a better solution.

Hi, I know that this is a bit old, but would you mind to suggest me something to avoid pushing a new screen? the camera seems to still working in the background because the console in IntelJIdea shows so.

Is it ok/valid to use a global key?
do you have any example before hand?

Thanks!.

**Comment by steve28100** [comment]
Is there any update on this issue? Have you find the solution/workaround @normancarcamo?
