### ISSUE TITLE
Crash on devices older than lollipop

### ISSUE THREAD

**Issue by rmtmckenzie** [rmtmckenzie/flutter_qr_mobile_vision#45]
I'm adding this here to track it and so that anyone else who runs across it sees.

If you get an error `java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener` it's because of this:
https://github.com/flutter/flutter/issues/21730

**Comment by salmanDevj** [comment]
I am getting the same error. I am new to dart and flutter, how to solve this issue?

**Comment by rmtmckenzie** [comment]
The fix had been merged into flutter's master so it should show up soon, but that depends a bit on their beta release schedule.

I'm fairly sure it's already been included in the `dev` branch though so you could switch to that by running`flutter channel dev` then `flutter upgrade`.
