### ISSUE TITLE
Camera has error on android but iOS is working & New example didn't gradle

### ISSUE THREAD

**Issue by samigimix** [rmtmckenzie/flutter_qr_mobile_vision#48]
Camera is working on iOS very well, but on **android** after camera opening, console print too much warnings and errors and didn't recognize any barcode. I searched in the internet and checked all solutions but it didn't work. Also your new update of **example** works on iOS but in android it has error in initializing **gradle**.

**It's gradle errors and warnings :** 

Exit code 1 from: /Users/saman/Downloads/flutter_qr_mobile_vision-master/example/android/gradlew -v:
Unzipping /Users/saman/.gradle/wrapper/dists/gradle-4.10.1-all/455itskqi2qtf0v2sja68alqd/gradle-4.10.1-all.zip to /Users/saman/.gradle/wrapper/dists/gradle-4.10.1-all/455itskqi2qtf0v2sja68alqd
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**It's camera errors and warnings on android :** 

I/cgr.qrmv.QrReader( 9168): Using new camera API.
I/cgr.qrmv.QrDetector( 9168): Making detector2 for formats: 1775
W/DynamiteModule( 9168): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule( 9168): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 9168): Cannot load feature, fall back to load whole module.
W/DynamiteModule( 9168): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
W/zygote64( 9168): Unsupported class loader
W/zygote64( 9168): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule( 9168): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule( 9168): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
W/zygote64( 9168): Unsupported class loader
W/zygote64( 9168): Skipping duplicate class check due to unsupported classloader
I/Vision  ( 9168): Loading library libbarhopper.so
I/zygote64( 9168): The ClassLoaderContext is a special shared library.
I/zygote64( 9168): The ClassLoaderContext is a special shared library.
I/zygote64( 9168): Do partial code cache collection, code=30KB, data=24KB
I/zygote64( 9168): After code cache collection, code=30KB, data=24KB
I/zygote64( 9168): Increasing code cache capacity to 128KB
I/Vision  ( 9168): Library not found: /data/user/0/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so
I/Vision  ( 9168): libbarhopper.so library load status: false
I/Vision  ( 9168): Request download for engine barcode
W/BarcodeNativeHandle( 9168): Native handle not yet available. Reverting to no-op handle.
I/CameraManagerGlobal( 9168): Connecting to camera service
W/ample.driverapp( 9168): type=1400 audit(0.0:3886): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=15533 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    ( 9168): Access denied finding property "persist.camera.cfa.packagelist"
I/cgr.qrmv.QrCameraC2( 9168): Setting af mode to: 4
I/zygote64( 9168): Background concurrent copying GC freed 10299(1229KB) AllocSpace objects, 2(40KB) LOS objects, 42% free, 32MB/56MB, paused 9.618ms total 87.426ms
I/zygote64( 9168): Background concurrent copying GC freed 147(136KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 64MB/88MB, paused 10.597ms total 78.638ms
I/zygote64( 9168): Background concurrent copying GC freed 76(110KB) AllocSpace objects, 0(0B) LOS objects, 14% free, 143MB/167MB, paused 87us total 113.433ms
I/zygote64( 9168): Clamp target GC heap from 199MB to 192MB
I/zygote64( 9168): Background concurrent copying GC freed 230(125KB) AllocSpace objects, 0(0B) LOS objects, 8% free, 175MB/192MB, paused 9.199ms total 90.236ms
I/zygote64( 9168): Starting a blocking GC Alloc
I/zygote64( 9168): Starting a blocking GC Alloc
W/DynamiteModule( 9168): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/zygote64( 9168): Clamp target GC heap from 215MB to 192MB
I/zygote64( 9168): Alloc concurrent copying GC freed 165(139KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 4.321ms total 41.392ms
I/zygote64( 9168): Starting a blocking GC Alloc
I/zygote64( 9168): Clamp target GC heap from 215MB to 192MB
I/zygote64( 9168): Alloc concurrent copying GC freed 127(34KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 205us total 27.966ms
I/zygote64( 9168): Forcing collection of SoftReferences for 7MB allocation
I/zygote64( 9168): Starting a blocking GC Alloc
I/DynamiteModule( 9168): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle( 9168): Cannot load feature, fall back to load whole module.
W/DynamiteModule( 9168): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/zygote64( 9168): Clamp target GC heap from 215MB to 192MB
I/zygote64( 9168): Alloc concurrent copying GC freed 247(53KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 234us total 25.763ms
W/zygote64( 9168): Throwing OutOfMemoryError "Failed to allocate a 8294412 byte allocation with 966840 free bytes and 944KB until OOM, max allowed footprint 201326592, growth limit 201326592"
I/zygote64( 9168): Starting a blocking GC Alloc
I/zygote64( 9168): Starting a blocking GC Alloc
I/DynamiteModule( 9168): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1800
I/DynamiteModule( 9168): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1800
I/zygote64( 9168): Clamp target GC heap from 215MB to 192MB
I/zygote64( 9168): Alloc concurrent copying GC freed 110(93KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 524us total 26.573ms
I/zygote64( 9168): Starting a blocking GC Alloc
I/zygote64( 9168): Clamp target GC heap from 215MB to 192MB
I/zygote64( 9168): Alloc concurrent copying GC freed 19(46KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 340us total 17.011ms
I/zygote64( 9168): Forcing collection of SoftReferences for 7MB allocation
I/zygote64( 9168): Starting a blocking GC Alloc
I/zygote64( 9168): Clamp target GC heap from 215MB to 192MB
I/zygote64( 9168): Alloc concurrent copying GC freed 73(49KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 442us total 16.746ms
W/zygote64( 9168): Throwing OutOfMemoryError "Failed to allocate a 8294416 byte allocation with 1012792 free bytes and 989KB until OOM, max allowed footprint 201326592, growth limit 201326592"
W/System.err( 9168): java.lang.OutOfMemoryError: Failed to allocate a 8294416 byte allocation with 1012792 free bytes and 989KB until OOM, max allowed footprint 201326592, growth limit 201326592
W/System.err( 9168): 	at com.github.rmtmckenzie.qrmobilevision.QrDetector2$QrImage.<init>(QrDetector2.java:63)

...

**Comment by rmtmckenzie** [comment]
That's weird. Do you have a recently updated version of play services on the android phone? Sometimes there can be problems with older versions.

**Comment by samigimix** [comment]
**I have the latest version of play services and flutter, I deleted zip file and run again, errors changed to :** 

* Error running Gradle:
Exit code 1 from: /Users/saman/Downloads/flutter_qr_mobile_vision-master/example/android/gradlew app:properties:
Starting a Gradle Daemon (subsequent builds will be faster)
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not resolve org.codehaus.mojo:animal-sniffer-annotations:1.14.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.analytics-library:shared:26.2.0 > com.google.guava:guava:23.0
      > Could not resolve org.codehaus.mojo:animal-sniffer-annotations:1.14.
         > Could not parse POM https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.pom
            > Could not resolve org.codehaus.mojo:animal-sniffer-parent:1.14.
               > Could not resolve org.codehaus.mojo:animal-sniffer-parent:1.14.
                  > Could not get resource 'https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14.pom'.
                     > Could not HEAD 'https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14.pom'. Received status code 502 from server: Bad Gateway

   > Could not resolve commons-logging:commons-logging:1.2.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.analytics-library:crash:26.2.0 > org.apache.httpcomponents:httpclient:4.5.2
      > Skipped due to earlier error
   > Could not resolve commons-codec:commons-codec:1.9.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.analytics-library:crash:26.2.0 > org.apache.httpcomponents:httpclient:4.5.2
      > Skipped due to earlier error
   > Could not resolve org.jetbrains:annotations:13.0.
     Required by:

         project : > com.android.tools.build:gradle:3.2.0 > org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.0 > org.jetbrains.kotlin:kotlin-stdlib:1.2.20
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools:sdklib:26.2.0 > com.android.tools.layoutlib:layoutlib-api:26.2.0
      > Skipped due to earlier error
   > Could not resolve com.sun.activation:javax.activation:1.2.0.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools:sdklib:26.2.0 > com.android.tools:repository:26.2.0
      > Skipped due to earlier error

   > Could not resolve org.glassfish.jaxb:jaxb-runtime:2.2.11.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools:sdklib:26.2.0 > com.android.tools:repository:26.2.0
      > Skipped due to earlier error
   > Could not resolve com.google.jimfs:jimfs:1.1.
     Required by:
         project : > com.android.tools.build:gradle:3.2.0 > com.android.tools.build:builder:3.2.0 > com.android.tools:sdklib:26.2.0 > com.android.tools:repository:26.2.0
      > Skipped due to earlier error
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2m 43s
Please review your Gradle project setup in the android/ folder.

**I confused that what is the problem ? and when i run my app also it has some more warnings :** 

Note: /Users/saman/flutter/.pub-cache/git/flutter_qr_mobile_vision-4085af7dc60c6a1af4bc6fe9a3dd0a5b33785697/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC1.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

**Comment by samigimix** [comment]
I run your example project on another system and it worked ! Maybe my flutter system files have some problems and I should reinstall flutter. Also the APK of my app ruined on another android phone but in my phone it doesn't ! I recommend to **reinstall flutter** files and test on **another phone**.

**Comment by samigimix** [comment]
How to dispose the camera ? I have a TabBar and I have a QrCamera in both tabs, when I taped the second tab, app crashed because the camera still is open on first tab. What's the solution ? @rmtmckenzie
