### ISSUE TITLE
Scaling is off on Android

### ISSUE THREAD

**Issue by rmtmckenzie** [rmtmckenzie/flutter_qr_mobile_vision#5]
On iOS, the current scaling method works. On Android, it doesn't.

Need to do check for Android vs iOS, and do old scaling method on Android.

**Comment by tristan2468** [comment]
I successfully edited your QrCamera.dart to return a different container from `build()` using `Platform.isAndroid` to test whether it is running on Android or not, and it seems to work.

**Comment by rmtmckenzie** [comment]
Okay, that's great. I've been working on a fix for this & a few other things (rotation doesn't work very well either, and supporting BoxFit properly), plus cleanup of the code to get it ready to publish.  Unfortunately I've been really busy lately and haven't had a chance to sit down and give it the couple of hours it needs....

**Comment by rmtmckenzie** [comment]
If you can do a PR that would be appreciated just so I can see what you did, although I probably won't end up using it directly as I've made some fairly significant changes to the underlying implementation.

**Comment by tristan2468** [comment]
All I did was uncomment you commented out Android section, but only returned that `Widget` if `Platform.isAndroid`. Otherwise it returned the same `Widget` as you usually do.
Hope that helps.

**Comment by rmtmckenzie** [comment]
Ah okay. That wasn't working very well for me on my phone.
