### ISSUE TITLE
Duplicate symbol in GoogleMobileVision and GoogleSignin

### ISSUE THREAD

**Issue by ghost** [rmtmckenzie/flutter_qr_mobile_vision#52]
```
duplicate symbol _OBJC_IVAR_$_MDMPasscodeCache._localAuthenticationInfo in:
        /Volumes/WD/New Users Home/craigfransen/IntelliJ_Projects/tagger_mob/ios/Pods/GoogleMobileVision/Detector/Frameworks/GoogleMobileVision.framework/GoogleMobileVision(MDMPasscodeCache_f189776e75765630b82721fafea64052.o)
        /Volumes/WD/New Users Home/craigfransen/IntelliJ_Projects/tagger_mob/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn(MDMPasscodeCache_42de90102bb6814d03833694aafcc99d.o)
```

I know this is not your issue, but wondering if you know of a workaround
______________________________________________
UPDATE: one workaround is to 

```
pod 'GoogleSignIn', '4.1.2'
```
And change the deploment target in XCode to 9.0
______________________________________________

Now that that is running, I'm getting black picture in QRCamera frame.  Sigh.

**Comment by rmtmckenzie** [comment]
Hmmm. Yeah that seems to be a problem that lots of people are seeing who try to use google sign in and google mobile vision. Unfortunate that google hasn't resolved it, although I'd bet that their current answer to that would be to recommend switching to firebase's mlkit as google mobile vision has been more or less deprecated.
