### ISSUE TITLE
QR Camera crashes on XiaoMi Note 1. SDK Version: 4.4.4 API level of 19

### ISSUE THREAD

**Issue by AmandaMML** [rmtmckenzie/flutter_qr_mobile_vision#54]
This is where I place my QrCamera, I've stated the box size. I've tested on another phone which has higher API level, it works. 

Center _qrReader = new Center(
      child: new SizedBox(
        child: new QrCamera(
          onError: (context, error) => Text(
            error.toString(),
            style: TextStyle(color: Colors.red),
          ),
          qrCodeCallback: (code) {
            setState(() {
              qr = code;
              ///if qr code matched, go to member pay
            });
          },
          child: new Center(
            child: Stack(
              children: <Widget>[
                SizedBox(
                  height: 250.0,
                  width: 250.0,
                  child: Container(
                    decoration: BoxDecoration(
                        border: Border.all(
                            color: const Color(0xFFF36F27), width: 2.0)),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );

**Comment by rmtmckenzie** [comment]
Could you include the crash log? If you run through flutter, you might not get the full android log so try running the android part directly (i.e. open up the android/build.gradle in android studio).

**Comment by AmandaMML** [comment]
Thank you for your reply. Is this the log you are referring? This is what I've got after running. 

11-23 10:51:53.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:51:53.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:51:53.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-23 10:51:58.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:51:58.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:51:58.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-23 10:52:03.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:52:03.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:52:03.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-23 10:52:05.970 22722-22728/? E/jdwp: Failed sending reply to debugger: Broken pipe
11-23 10:52:06.310 22722-22722/? E/dalvikvm: Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method io.flutter.plugin.platform.PlatformPlugin.setSystemChromeApplicationSwitcherDescription
11-23 10:52:06.340 209-466/? E/cutils: Failed to mkdirat(/storage/sdcard1/Android/data/com.example.task5/files): No space left on device
11-23 10:52:08.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:52:08.660 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:52:08.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-23 10:52:09.520 22722-22722/com.example.task5 E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener
        at io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>(FlutterView.java:1044)
        at io.flutter.view.FlutterView.createSurfaceTexture(FlutterView.java:1030)
        at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.onMethodCall(QrMobileVisionPlugin.java:100)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:5052)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
        at dalvik.system.NativeStart.main(Native Method)
11-23 10:52:09.520 22722-22722/com.example.task5 A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
11-23 10:52:09.520 22722-22722/com.example.task5 A/libc: Fatal signal 6 (SIGABRT) at 0x000058c2 (code=-6), thread 22722 (m.example.task5)
11-23 10:52:13.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:52:13.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:52:13.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-23 10:52:18.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:52:18.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:52:18.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-23 10:52:23.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:52:23.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:52:23.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]
11-23 10:52:28.640 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
11-23 10:52:28.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
11-23 10:52:28.670 367-367/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWWAN-PE] unknown deliver target [OS-Agent]

**Comment by AmandaMML** [comment]
And then this is from the console.

> Launching lib\main.dart on HM NOTE 1LTE in debug mode...
> Initializing gradle...
> Resolving dependencies...
> Gradle task 'assembleDebug'...
> Built build\app\outputs\apk\debug\app-debug.apk.
> Syncing files to device HM NOTE 1LTE...
> I/dalvikvm(21105): Could not find method android.graphics.SurfaceTexture.setOnFrameAvailableListener, referenced from method io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>
> W/dalvikvm(21105): VFY: unable to resolve virtual method 1108: Landroid/graphics/SurfaceTexture;.setOnFrameAvailableListener (Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;Landroid/os/Handler;)V
> D/dalvikvm(21105): VFY: replacing opcode 0x6e at 0x0015
> E/flutter (21105): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener
> E/flutter (21105): 	at io.flutter.view.FlutterView$SurfaceTextureRegistryEntry.<init>(FlutterView.java:1044)
> E/flutter (21105): 	at io.flutter.view.FlutterView.createSurfaceTexture(FlutterView.java:1030)
> E/flutter (21105): 	at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.onMethodCall(QrMobileVisionPlugin.java:100)
> E/flutter (21105): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
> E/flutter (21105): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
> E/flutter (21105): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter (21105): 	at android.os.MessageQueue.next(MessageQueue.java:138)
> E/flutter (21105): 	at android.os.Looper.loop(Looper.java:123)
> E/flutter (21105): 	at android.app.ActivityThread.main(ActivityThread.java:5052)
> E/flutter (21105): 	at java.lang.reflect.Method.invokeNative(Native Method)
> E/flutter (21105): 	at java.lang.reflect.Method.invoke(Method.java:515)
> E/flutter (21105): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
> E/flutter (21105): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
> E/flutter (21105): 	at dalvik.system.NativeStart.main(Native Method)
> E/flutter (21105): 
> F/flutter (21105): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
> F/libc    (21105): Fatal signal 6 (SIGABRT) at 0x00005271 (code=-6), thread 21105 (m.example.task5)
> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> Build fingerprint: 'Xiaomi/dior/dior:4.4.4/KTU84P/V9.2.3.0.KHIMIEK:user/release-keys'
> Revision: '0'
> pid: 21105, tid: 21105, name: m.example.task5  >>> com.example.task5 <<<
> signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
>     r0 00000000  r1 00005271  r2 00000006  r3 00000000
>     r4 00000006  r5 0000000b  r6 00005271  r7 0000010c
>     r8 be8e911c  r9 61d0ee50  sl 60c1baa0  fp 61d0ee50
>     ip be8e9118  sp be8e8fe8  lr 4005b1d1  pc 4006a12c  cpsr 000f0010
>     d0  0000000000000000  d1  0000000000000000
>     d2  0000000000000000  d3  0000000000000000
>     d4  6563616672755365  d5  2865727574786554
>     d6  5672657474756c46  d7  6176616a2e776569
>     d8  0000000000000000  d9  0000000000000000
>     d10 0000000000000000  d11 0000000000000000
>     d12 0000000000000000  d13 0000000000000000
>     d14 0000000000000000  d15 0000000000000000
>     d16 6378456b63656843  d17 65286e6f69747065
>     d18 766c616420746109  d19 65747379732e6b69
>     d20 65766974614e2e6d  d21 616d2e7472617453
>     d22 766974614e286e69  d23 646f6874654d2065
>     d24 0000000000000000  d25 0000000000000000
>     d26 0000000000000000  d27 4000000000000000
>     d28 40008df2d49d41f1  d29 3fb0f4a31edab38b
>     d30 3ff0000000000000  d31 3f4de16b9c24a98f
>     scr 20000012
> backtrace:
>     #00  pc 0002212c  /system/lib/libc.so (tgkill+12)
>     #01  pc 000131cd  /system/lib/libc.so (pthread_kill+48)
>     #02  pc 000133e1  /system/lib/libc.so (raise+10)
>     #03  pc 000120a3  /system/lib/libc.so
>     #04  pc 000219e0  /system/lib/libc.so (abort+4)
>     #05  pc 0000d9a7  /data/app-lib/com.example.task5-2/libflutter.so
> stack:
>          be8e8fa8  60003737  [stack:21129]
>          be8e8fac  6016ec4b  /data/app-lib/com.example.task5-2/libflutter.so
>          be8e8fb0  64d21c41  
>          be8e8fb4  605bf179  /data/app-lib/com.example.task5-2/libflutter.so
>          be8e8fb8  00000002  
>          be8e8fbc  be8e9078  [stack]
>          be8e8fc0  60194d98  /data/app-lib/com.example.task5-2/libflutter.so
>          be8e8fc4  00000000  
>          be8e8fc8  00000070  
>          be8e8fcc  64d21bd8  
>          be8e8fd0  400b013d  /system/lib/liblog.so
>          be8e8fd4  601555f8  /data/app-lib/com.example.task5-2/libflutter.so
>          be8e8fd8  64d21b30  
>          be8e8fdc  00000000  
>          be8e8fe0  40096398  
>          be8e8fe4  400b02e1  /system/lib/liblog.so (__android_log_write+212)
>     #00  be8e8fe8  00000006  
>          be8e8fec  0000000b  
>          be8e8ff0  00005271  
>          be8e8ff4  be8e9118  [stack]
>          be8e8ff8  be8e9118  [stack]
>          be8e8ffc  4005b1d1  /system/lib/libc.so (pthread_kill+52)
>     #01  be8e9000  00000006  
>          be8e9004  00000000  
>          be8e9008  00000003  
>          be8e900c  4005b3e5  /system/lib/libc.so (raise+14)
>     #02  be8e9010  be8e901c  [stack]
>          be8e9014  4005a0a7  /system/lib/libc.so
> memory near r1:
>     00005250 ffffffff ffffffff ffffffff ffffffff  
>     00005260 ffffffff ffffffff ffffffff ffffffff  
>     00005270 ffffffff ffffffff ffffffff ffffffff  
>     00005280 ffffffff ffffffff ffffffff ffffffff  
>     00005290 ffffffff ffffffff ffffffff ffffffff  
>     000052a0 ffffffff ffffffff ffffffff ffffffff  
>     000052b0 ffffffff ffffffff ffffffff ffffffff  
>     000052c0 ffffffff ffffffff ffffffff ffffffff  
>     000052d0 ffffffff ffffffff ffffffff ffffffff  
>     000052e0 ffffffff ffffffff ffffffff ffffffff  
>     000052f0 ffffffff ffffffff ffffffff ffffffff  
>     00005300 ffffffff ffffffff ffffffff ffffffff  
>     00005310 ffffffff ffffffff ffffffff ffffffff  
>     00005320 ffffffff ffffffff ffffffff ffffffff  
>     00005330 ffffffff ffffffff ffffffff ffffffff  
>     00005340 ffffffff ffffffff ffffffff ffffffff  
> memory near r6:
>     00005250 ffffffff ffffffff ffffffff ffffffff  
>     00005260 ffffffff ffffffff ffffffff ffffffff  
>     00005270 ffffffff ffffffff ffffffff ffffffff  
>     00005280 ffffffff ffffffff ffffffff ffffffff  
>     00005290 ffffffff ffffffff ffffffff ffffffff  
>     000052a0 ffffffff ffffffff ffffffff ffffffff  
>     000052b0 ffffffff ffffffff ffffffff ffffffff  
>     000052c0 ffffffff ffffffff ffffffff ffffffff  
>     000052d0 ffffffff ffffffff ffffffff ffffffff  
>     000052e0 ffffffff ffffffff ffffffff ffffffff  
>     000052f0 ffffffff ffffffff ffffffff ffffffff  
>     00005300 ffffffff ffffffff ffffffff ffffffff  
>     00005310 ffffffff ffffffff ffffffff ffffffff  
>     00005320 ffffffff ffffffff ffffffff ffffffff  
>     00005330 ffffffff ffffffff ffffffff ffffffff  
>     00005340 ffffffff ffffffff ffffffff ffffffff  
> memory near r8:
>     be8e90fc 00000003 6016ec45 0000004d 41637308  
>     be8e910c 605c0859 00000002 60bbd6a0 00000000  
>     be8e911c 76900025 41637308 64200021 41637308  
>     be8e912c 00000002 0490001d 41637308 be8e9154  
>     be8e913c 64d21840 60c1baac 64d21858 6273ea58  
>     be8e914c 605ebbc1 00000001 00000000 00000001  
>     be8e915c 605ca1ad 41637308 00000001 0000004a  
>     be8e916c 5bd61a08 60c1bab4 be8e91c8 f22ebac3  
>     be8e917c 00006289 416db3fa 64d21840 64d21858  
>     be8e918c 64d21858 00000000 00000000 00000000  
>     be8e919c 00000000 00000021 0000001c 64fbabe0  
>     be8e91ac 00000000 61d0ee50 6273ea80 61d0ee50  
>     be8e91bc 6273ea58 00000001 400e2ebd 64d21df0  
>     be8e91cc 400e2ef1 5bd61a08 00000000 60c1bbe0  
>     be8e91dc be8e9208 5bd619c0 400e088d be8e9200  
>     be8e91ec 605cca97 64d21df0 00000000 00000042  
> memory near r9:
>     61d0ee30 00000000 0000001b 00000000 60148b52  
>     61d0ee40 0000006f 00000000 00000018 00000013  
>     61d0ee50 6273ea58 400961c8 00000010 00000023  
>     61d0ee60 0000000c 00000005 23233432 6c6c6166  
>     61d0ee70 6b636162 fdd6fc00 088d0ee2 00000023  
>     61d0ee80 60bd2e0c 00000001 61d0eed8 00000004  
>     61d0ee90 00000008 fec6fc2d 00010ee2 0000003b  
>     61d0eea0 00000027 00000001 7379732f 2f6d6574  
>     61d0eeb0 746e6f66 6f4e2f73 61536f74 724f736e  
>     61d0eec0 2d617969 75676552 2e72616c 00667474  
>     61d0eed0 00010002 0000002b 61d0ef00 61d13008  
>     61d0eee0 61d130c8 61d0b7a0 00000000 00000000  
>     61d0eef0 00000000 60bc187c 00000000 0000008b  
>     61d0ef00 60bd2e30 00000001 00000001 00000046  
>     61d0ef10 00050190 00010000 00000000 00000000  
>     61d0ef20 00000000 00000000 61d0ee60 61d0eea0  
> memory near sl:
>     60c1ba80 60bc3a3c 00000009 60c1baa0 00000013  
>     60c1ba90 60c1baa0 60c1ba80 00000000 0000005b  
>     60c1baa0 60bc3ac0 00000002 60c1baac 00000000  
>     60c1bab0 00000000 00000000 61d0ee50 61d0ee50  
>     60c1bac0 61d0ee54 61d0ee54 00000000 00000000  
>     60c1bad0 400961e0 00000004 3a706f00 5bd619c0  
>     60c1bae0 00000042 54646500 736b7361 00000000  
>     60c1baf0 00000058 0000001b 42082ef8 400961d0  
>     60c1bb00 4f534a2e 6a624f4e 00000018 0000006b  
>     60c1bb10 00000001 00000050 00000000 00000000  
>     60c1bb20 00000042 00000042 fffffffe 60c1ba68  
>     60c1bb30 60c1baa0 0000004a 0000004a fffffffe  
>     60c1bb40 6273fda8 00000000 0000004b 0000004b  
>     60c1bb50 fffffffe 6267f940 00000000 00000000  
>     60c1bb60 00000000 00000000 00000000 00000000  
>     60c1bb70 00000068 0000006b 004c0284 03800050  
> memory near fp:
>     61d0ee30 00000000 0000001b 00000000 60148b52  
>     61d0ee40 0000006f 00000000 00000018 00000013  
>     61d0ee50 6273ea58 400961c8 00000010 00000023  
>     61d0ee60 0000000c 00000005 23233432 6c6c6166  
>     61d0ee70 6b636162 fdd6fc00 088d0ee2 00000023  
>     61d0ee80 60bd2e0c 00000001 61d0eed8 00000004  
>     61d0ee90 00000008 fec6fc2d 00010ee2 0000003b  
>     61d0eea0 00000027 00000001 7379732f 2f6d6574  
>     61d0eeb0 746e6f66 6f4e2f73 61536f74 724f736e  
>     61d0eec0 2d617969 75676552 2e72616c 00667474  
>     61d0eed0 00010002 0000002b 61d0ef00 61d13008  
>     61d0eee0 61d130c8 61d0b7a0 00000000 00000000  
>     61d0eef0 00000000 60bc187c 00000000 0000008b  
>     61d0ef00 60bd2e30 00000001 00000001 00000046  
>     61d0ef10 00050190 00010000 00000000 00000000  
>     61d0ef20 00000000 00000000 61d0ee60 61d0eea0  
> memory near ip:
>     be8e90f8 00000020 00000003 6016ec45 0000004d  
>     be8e9108 41637308 605c0859 00000002 60bbd6a0  
>     be8e9118 00000000 76900025 41637308 64200021  
>     be8e9128 41637308 00000002 0490001d 41637308  
>     be8e9138 be8e9154 64d21840 60c1baac 64d21858  
>     be8e9148 6273ea58 605ebbc1 00000001 00000000  
>     be8e9158 00000001 605ca1ad 41637308 00000001  
>     be8e9168 0000004a 5bd61a08 60c1bab4 be8e91c8  
>     be8e9178 f22ebac3 00006289 416db3fa 64d21840  
>     be8e9188 64d21858 64d21858 00000000 00000000  
>     be8e9198 00000000 00000000 00000021 0000001c  
>     be8e91a8 64fbabe0 00000000 61d0ee50 6273ea80  
>     be8e91b8 61d0ee50 6273ea58 00000001 400e2ebd  
>     be8e91c8 64d21df0 400e2ef1 5bd61a08 00000000  
>     be8e91d8 60c1bbe0 be8e9208 5bd619c0 400e088d  
>     be8e91e8 be8e9200 605cca97 64d21df0 00000000  
> memory near sp:
>     be8e8fc8 00000070 64d21bd8 400b013d 601555f8  
>     be8e8fd8 64d21b30 00000000 40096398 400b02e1  
>     be8e8fe8 00000006 0000000b 00005271 be8e9118  
>     be8e8ff8 be8e9118 4005b1d1 00000006 00000000  
>     be8e9008 00000003 4005b3e5 be8e901c 4005a0a7  
>     be8e9018 be8e911c ffffffdf 40092000 be8e904c  
>     be8e9028 be8e904c be8e904c 00000003 be8e9074  
>     be8e9038 be8e904c 400699e4 400b013d 605c99ab  
>     be8e9048 be8e9074 00000071 0000006c 64d21b30  
>     be8e9058 41637308 be8e9154 00000000 605c19c1  
>     be8e9068 601906ff 00000002 0000006d 60bc39b0  
>     be8e9078 60bc33a0 60c10798 00000000 00000000  
>     be8e9088 00000000 64d21bd8 64d21c44 64d21c57  
>     be8e9098 00000081 0000007f 64d21bd8 64d21c44  
>     be8e90a8 00000010 60bc39c4 00001002 00000006  
>     be8e90b8 00000000 00000000 00000000 be8e9078  
> code around pc:
>     4006a10c e8bd00f0 e3700a01 912fff1e e2600000  
>     4006a11c ea006e05 e92d50f0 e3a07f43 ef000000  
>     4006a12c e8bd50f0 e3700a01 912fff1e e2600000  
>     4006a13c ea006dfd e92d50f0 e3a070ee ef000000  
>     4006a14c e8bd50f0 e3700a01 912fff1e e2600000  
>     4006a15c ea006df5 f200429a bf0080b9 f040f891  
>     4006a16c 4001e92d f2c02a04 2a1080a5 8093f2c0  
>     4006a17c f2c02a20 2a408088 ea4fdb7f f1bc1c92  
>     4006a18c dd6c0f0a 0600e92d 0f40f1bc f500dd4a  
>     4006a19c f5016e80 ebae7920 ea4f0e09 ea4f5e4e  
>     4006a1ac f50e5e5e ebbc7e20 dd3b1f9e f04fbfc4  
>     4006a1bc ebd9090a dd35199e 0a0eeb01 0a3ff02a  
>     4006a1cc 1c9eebac bfd245e1 0c09ebac f04f46e1  
>     4006a1dc f8910c00 f891f240 f921f280 f921028d  
>     4006a1ec f8da428d f1b93000 f9000901 f900028d  
>     4006a1fc f10a428d d1ee0a40 0f00f1bc f5bcd02b  
> code around lr:
>     4005b1b0 447b4b13 42b3e010 6a1ed10e 44784811  
>     4005b1c0 ec4af7fb e9e6f00d 46224631 efa8f00e  
>     4005b1d0 d00a3001 e00b2400 2b00681b 480ad1eb  
>     4005b1e0 44782403 ec38f7fb f001e002 6804f9ff  
>     4005b1f0 f9fcf001 46206005 bf00bd70 0003b206  
>     4005b200 0003b1fa 0003b1f2 0003b1ce bf7ef7ff  
>     4005b210 4a3e4b3d e92d447b b08b43f0 4606589c  
>     4005b220 6823460d 930946a1 f9e0f001 8000f8d0  
>     4005b230 d0482d00 f0104628 280ff8f5 d8444604  
>     4005b240 ffe4f7ff d1064286 4629200f e8b0f00d  
>     4005b250 d03c2800 482ee02e f7fb4478 482deb7c  
>     4005b260 e0154478 d11342b0 482b6a06 f7fb4478  
>     4005b270 4a2aebf4 46332120 a801447a f96cf013  
>     4005b280 a8012101 fc8af01a 46061c42 e011d104  
>     4005b290 28006800 e02cd1e6 46294630 f00d4622  
>     4005b2a0 1c43e8ec d11e4607 f9a0f001 29046801  
> Lost connection to device.
>

**Comment by rmtmckenzie** [comment]
Ah that's the one =) this is the problem

```java.lang.NoSuchMethodError: android.graphics.SurfaceTexture.setOnFrameAvailableListener```

That's an issue with flutter itself though, and has been fixed for about a month. See #45.

**Comment by AmandaMML** [comment]
Thank you so much! :D
