### ISSUE TITLE
Camera FPS too low - iPhone 5s

### ISSUE THREAD

**Issue by d-mh** [rmtmckenzie/flutter_qr_mobile_vision#56]
First of all - big thanks for this plugin!

I have a problem with camera fps on iPhone 5s - it is not smooth, its working very slow.

I set barcode type only to QR_CODE - its a little better, but still not usable.

On my old Android Samsung S4 (i9505) its working nice and smooth. Do you know what could be done to optimise it?

**Comment by jaumard** [comment]
Did you try in release mode ? Of course debug mode is slow and laggy (it's a general point on flutter apps) but normally it should be ok on release mode

**Comment by Afulton11** [comment]
I tried in release mode on an iPhone 6 and the camera is still very slow and laggy. Although it can still scan a qr code relatively quickly.

**Comment by shkatulo** [comment]
I fixed this on iOS and sent pull request to this repository: https://github.com/rmtmckenzie/flutter_qr_mobile_vision/pull/94

Until PR is accepted, you can use this in pubspec.yaml:
`  qr_mobile_vision:
    git:
      url: https://github.com/shkatulo/flutter_qr_mobile_vision.git`

Also you may need to update flutter packages.

**Comment by alexisnaud** [comment]
It's working for me, thanks! @shkatulo

**Comment by qimingweng** [comment]
Any update on this issue and pull request?

**Comment by qimingweng** [comment]
Tested #94 and just adding this comment to say it works for me on physical iPhone (much faster FPS on camera).

**Comment by d-mh** [comment]
Thanks @qimingweng for your confirmation. I am closing this issue

**Comment by qimingweng** [comment]
@d-mh just curious why you are closing the issue, as I don't believe this is solved in the main library? The PR from #94 has not been merged yet.

**Comment by d-mh** [comment]
@qimingweng you are right

**Comment by booooza** [comment]
Same issue here with iPhone 6. @rmtmckenzie any chance you can look into this? It turns the otherwise great library quite unusable for me. Thank you :)

**Comment by rmtmckenzie** [comment]
@booooza try with version 1.0.0, it should be a lot better =)

**Comment by booooza** [comment]
@rmtmckenzie jup, can confirm rendering with version 1.0.0 is smooth 👍 thanks
