### ISSUE TITLE
black screen on oppo find 7a

### ISSUE THREAD

**Issue by gumenza01** [rmtmckenzie/flutter_qr_mobile_vision#61]
E/CameraDevice-0-LE(21927): Surface with size (w=800, h=600) and format 0x23 is not valid, size not in valid set: [1440x1080, 1280x960, 1280x720, 864x480, 800x480, 720x480, 640x480, 576x432, 480x320, 384x288, 352x288, 320x240, 240x160, 176x144]
W/CameraDevice-JV-0(21927): Stream configuration failed
E/CameraCaptureSession(21927): Session 0: Failed to create capture session; configuration failed
I/System.out(21927): ### Configuration Fail ###

**Comment by rmtmckenzie** [comment]
Closing as this might be fixed on 1.0.0.
