### ISSUE TITLE
Add AndroidX Support

### ISSUE THREAD

**Issue by alphamikle** [rmtmckenzie/flutter_qr_mobile_vision#67]
Please, change android.support libraries to its analogs from androidx library:
For build project with this depency i changed:
In QrCameraC2.java
android.support.annotation.NonNull -> androidx.annotation.NonNull
in QrMobileVisionPlugin.java
android.support.v4.app.ActivityCompat -> androidx.core.app.ActivityCompat
After that project build correct

**Comment by rmtmckenzie** [comment]
Hi! This is definitely on my list of stuff to do. I'm really hoping to get an update out soon with a whole bunch of changes including but I'm not 100% sure when I'll get to it. If I don't manage in the next couple days I'll try to push an update out for this specific issue....

**Comment by alphamikle** [comment]
Thanks for it! Your lib is very good!
