### ISSUE TITLE
FIDO2

### ISSUE THREAD

**Issue by gedw99** [rmtmckenzie/flutter_qr_mobile_vision#68]
i have a FIDO2 hardware device that i want to use with this lib.

Does it support FIDO2 yet ?

I can help

**Comment by rmtmckenzie** [comment]
That's very much outside the scope of this plugin - it isn't meant directly for FIDO2 but instead a general QR scanner for all sorts of purposes.

If you're interested in working on FIDO2 hardware support you'd be better off making a separate plugin, which could theoretically use this as a dependency (although it would make more sense to me to have two completely separate plugins and do the choice about what to use in the app's logic)

**Comment by gedw99** [comment]
@rmtmckenzie thanks you right - separate plugin for fido2
