### ISSUE TITLE
Issue with AndroidX

### ISSUE THREAD

**Issue by smoooochy** [rmtmckenzie/flutter_qr_mobile_vision#72]
Hi,
I have a problem compiling the newest version with a new flutter project that was set up for AndroidX

these are the errors I am getting:

`E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:27: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrMobileVisionPlugin.java:6: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:127: error: cannot find symbol
                public void onOpened(@NonNull CameraDevice device) {
                                      ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:133: error: cannot find symbol
                public void onDisconnected(@NonNull CameraDevice device) {
                                            ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:137: error: cannot find symbol
                public void onError(@NonNull CameraDevice device, int error) {
                                     ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:223: error: cannot find symbol
                public void onConfigured(@NonNull CameraCaptureSession session) {
                                          ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:229: error: cannot find symbol
                public void onConfigureFailed(@NonNull CameraCaptureSession session) {
                                               ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                            ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                                                                   ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                                                                                                    ^
  symbol: class NonNull
E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrMobileVisionPlugin.java:118: error: cannot find symbol
                        ActivityCompat.requestPermissions(context,
                        ^
  symbol:   variable ActivityCompat
  location: class QrMobileVisionPlugin
Note: E:\flutter\.pub-cache\hosted\pub.dartlang.org\qr_mobile_vision-0.2.2\android\src\main\java\com\github\rmtmckenzie\qrmobilevision\QrCameraC1.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

this is the build.gradle:

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.gatg.asdf"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
`

any idea of what I am missing?

edit: sorry, no clue why the lower part is not correctly code formatted...

**Comment by rmtmckenzie** [comment]
Hmmm. Can you confirm that you have 
```
android.enableJetifier=true
android.useAndroidX=true
```
set in your gradle.properties file?

**Comment by smoooochy** [comment]
Oh well, I tried to migrate via Android Studio. The documentation on android.com was not clear on that those two flags are required. Thanks that solved it! And such a quick reply :+1:

**Comment by rmtmckenzie** [comment]
=) android studio should have set those as part of the refactor, but glad I could help

**Comment by AmitParel** [comment]
@rmtmckenzie I am facing same issue as I checked I have already placed the following code in gradle.properties
android.enableJetifier=true
android.useAndroidX=true
