### ISSUE TITLE
'native_device_orientation/NativeDeviceOrientationPlugin.h' file not found on xcode

### ISSUE THREAD

**Issue by lunwhl** [rmtmckenzie/flutter_qr_mobile_vision#76]
I have implemented this package in my project and everything runs good with android until I wanted to deploy my flutter app into my iPhone.

I hit the error of 'native_device_orientation/NativeDeviceOrientationPlugin.h' file not found in xcode when I was trying to deploy to my iPhone which I think this file is needed for this package to run.

Any suggestion to fix this?

**Comment by rmtmckenzie** [comment]
That's strange. Try running `pod install` in the ios directory of your build. And can you paste in the result of running `flutter doctor -v`?

**Comment by lunwhl** [comment]
hi kenzie, thank for the quick reply.
The picture below are the result of flutter doctor -v.
<img width="579" alt="Screen Shot 2019-03-15 at 10 27 18 AM" src="https://user-images.githubusercontent.com/19488286/54404018-14c34800-470d-11e9-9cf9-e763e0ea8fb6.png">

**Comment by lunwhl** [comment]
Just in case someone is facing the same issue as me.
The problem was mainly cause by the PodFile in /ios.

I have this issue resolved by follow the link below.
https://github.com/flutter/flutter/issues/16246#issuecomment-454306108
