### ISSUE TITLE
Keep switching scan screen crash on iPhone 6

### ISSUE THREAD

**Issue by lunwhl** [rmtmckenzie/flutter_qr_mobile_vision#77]
Thank for the plugin.
I have deploy my app with the package in my iPhone 6.

When I keep switching from screen 1 to scan screen and scan screen to screen 1 then the app crash.

Seem like something heavy running in the background and running out of memory.

Any idea on this?

**Comment by rmtmckenzie** [comment]
Yeah this has been reported by other users as well, see #64. I'll close this and update on that thread.  But unfortunately I haven't been able to figure out what's going on yet, although I haven't had that much time to spend on it. I'm hoping to fix it soon though...
