### ISSUE TITLE
Flutter: Build ios error: OS version does not support use of thread local variables in l1877 for architecture x86_64 (iOS 8)

### ISSUE THREAD

**Issue by williamdias** [rmtmckenzie/flutter_qr_mobile_vision#78]
Hi. I am not able to build my project for the iOS simulator after adding flutter_qr_mobile_vision if Deployment Target is set to iOS 8. I can only build it if iOS >= 9. 

> Launching test/actions/sign_request_action_test.dart on iPhone 6 in debug mode...
Running pod install...                                             10.4s
                                                                                                                                                               ├─Assembling Flutter resources...                           2.4s                                                                                              └─Compiling, linking and signing...                         1.3s
Xcode build done.                                           12.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: targeted OS version does not support use of thread local variables in l1877 for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rmtmckenzie** [comment]
This plugin won't work on the simulator at all since it required a camera. I'm going to close this for now, but if anyone needs to support iOS 8 and can't get it to work I encourage you to open a new issue.
