### ISSUE TITLE
Camera view not starting.

### ISSUE THREAD

**Issue by tristan2468** [rmtmckenzie/flutter_qr_mobile_vision#8]
I have the QrCamera widget in my widget tree, and the following Exception occurs.

`'package:qr_mobile_vision/qr_mobile_vision.dart': Failed assertion: line 43 pos 12: 'details is Map<String, dynamic>': is not true.`

This happens on both Android and iOS.

**Comment by rmtmckenzie** [comment]
Try the barcode-cleanup branch. It has a couple of fixes to get this working in Dart 2. 

I'm going to try to clean the plugin up a bit over the weekend and maybe even publish it on pub =).
