### ISSUE TITLE
Stop Camera inafter have an result

### ISSUE THREAD

**Issue by os20** [rmtmckenzie/flutter_qr_mobile_vision#80]
How can I stop the camera after receiving the first result?

**Comment by rmtmckenzie** [comment]
I'm still working on an update that will make this easier, but for now you can pass in a GlobalKey and use it to call CameraState's stop. See this comment another issue: https://github.com/rmtmckenzie/flutter_qr_mobile_vision/issues/55#issuecomment-444958997
