### ISSUE TITLE
Not working on OPO 6T

### ISSUE THREAD

**Issue by miguelpruivo** [rmtmckenzie/flutter_qr_mobile_vision#82]
This doesn't seem to be working with OPO 6T. Other than that, I've not found any issues.

**Comment by Afulton11** [comment]
Yeah I'm having the same issue.
Works fine on my Google Pixel, but using a OnePlus 6T, a QR code is never read.

**Comment by sharpsan** [comment]
Experiencing this issue as well.

**Comment by mkiisoft** [comment]
Same issue... OP6T not working, no issues with iPhone 6s.

**Comment by SebastianRuettger** [comment]
OnePlus 6 here, same issue

**Comment by gamelaster** [comment]
OnePlus 6T, same.... how is this possible? 😀

**Comment by okarpov** [comment]
any update on it? has been solved? other phones it is not working on?

**Comment by GyuriMajercsik** [comment]
the same here, OP6

**Comment by tudor07** [comment]
I have the same issue, not working with OP6

**Comment by gamelaster** [comment]
I don't want to make an advertisement for other project, but I was looking for alternative, and found only this [flutter_barcode_reader](https://github.com/apptreesoftware/flutter_barcode_reader) works fine on OP 6T (it supports also QR codes)

**Comment by okarpov** [comment]
> I don't want to make an advertisement for other project, but I was looking for alternative, and found only this [flutter_barcode_reader](https://github.com/apptreesoftware/flutter_barcode_reader) works fine on OP 6T (it supports also QR codes)

I need to be able to read different formats especially PDF417, can that one read such?

**Comment by rmtmckenzie** [comment]
This is a bit of an old thread now, but I've released a new version which uses FirebaseMobileVision library instead of GoogleMobileVision. If anyone with an Oppo device wants to test it out, I'd appreciate the feedback =)

**Comment by gamelaster** [comment]
@rmtmckenzie Hi, I had issues with this library on mine OnePlus 6T, if I will not forgot, I will test if the new version works. Thank you really for your work!

BTW: If I will not provide feedback here, please, mention me here, thanks
