### ISSUE TITLE
Wrong barcode data

### ISSUE THREAD

**Issue by kavin014** [rmtmckenzie/flutter_qr_mobile_vision#85]
Using back camera to scan EAN_13 type barcode, occasionally gets random data as scanned.
Getting wrong data even there is no barcode visible to the camera.

How could I sort out this issue?
Using version 0.2.2

**Comment by rmtmckenzie** [comment]
Using FirebaseMobileVision library which has hopefully been updated. I'm going to close this for now but if you see this again please let me know. I'd also recommend screening the data for it being somewhat like what you expect - I'm just returning whatever I get from the QR scanning library so if it's invalid I won't really know.,
