### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by ylmsolutionsltd** [rmtmckenzie/flutter_qr_mobile_vision#86]
When i accept  SMS permission  the app crash on your scanner  which is not part of the widget screen?!
The scanner widget is initialzied after completing the sign up process and moving to another dart class,

E/AndroidRuntime( 5893): Process: il.co.ylm.inspector_native, PID: 5893
E/AndroidRuntime( 5893): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {il.co.ylm.inspector_native/il.co.ylm.inspector_native.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'com.github.rmtmckenzie.qrmobilevision.QrReader com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin$ReadingInstance.reader' on a null object reference
E/AndroidRuntime( 5893): at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
E/AndroidRuntime( 5893): at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
E/AndroidRuntime( 5893): at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime( 5893): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
E/AndroidRuntime( 5893): at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 5893): at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 5893): at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime( 5893): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5893): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 5893): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime( 5893): Caused by: java.lang.NullPointerException: Attempt to read from field 'com.github.rmtmckenzie.qrmobilevision.QrReader com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin$ReadingInstance.reader' on a null object reference
E/AndroidRuntime( 5893): at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.stopReader(QrMobileVisionPlugin.java:73)
E/AndroidRuntime( 5893): at com.github.rmtmckenzie.qrmobilevision.QrMobileVisionPlugin.onRequestPermissionsResult(QrMobileVisionPlugin.java:60)
E/AndroidRuntime( 5893): at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:203)
E/AndroidRuntime( 5893): at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:129)
E/AndroidRuntime( 5893): at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime( 5893): at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7737)
E/AndroidRuntime( 5893): at android.app.Activity.dispatchActivityResult(Activity.java:7560)
E/AndroidRuntime( 5893): at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)

**Comment by yongjhih** [comment]
https://github.com/yongjhih/flutter_qr_mobile_vision/commit/b33322829634e87724c9acf326e90c9e66d99108

**Comment by v0l** [comment]
@yongjhih pls PR this?

**Comment by rmtmckenzie** [comment]
@v0l  I've integrated that fix into 0.3.1.
