### ISSUE TITLE
Tossing an AndroidX related error log directly after implementation...

### ISSUE THREAD

**Issue by AKushWarrior** [rmtmckenzie/flutter_qr_mobile_vision#89]
The app was working fine before I implemented your plug-in (and still is working on IOS). The gradle promptly crashed when I attempted to build/run the app on an Android (Galaxy S8, SM G950U). Is the plug-in migrated to AndroidX? Is there additional steps I may have to take in order to work this out? I've run Android Studio's "Refactor/Migrate to AndroidX" but it's not finding any issues. 

(Console Error Log Below)

/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:27: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrMobileVisionPlugin.java:6: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:127: error: cannot find symbol
                public void onOpened(@NonNull CameraDevice device) {
                                      ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:133: error: cannot find symbol
                public void onDisconnected(@NonNull CameraDevice device) {
                                            ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:137: error: cannot find symbol
                public void onError(@NonNull CameraDevice device, int error) {
                                     ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:223: error: cannot find symbol
                public void onConfigured(@NonNull CameraCaptureSession session) {
                                          ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:229: error: cannot find symbol
                public void onConfigureFailed(@NonNull CameraCaptureSession session) {
                                               ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                            ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                                                                   ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC2.java:242: error: cannot find symbol
            public void onCaptureCompleted(@NonNull CameraCaptureSession session, @NonNull CaptureRequest request, @NonNull TotalCaptureResult result) {
                                                                                                                    ^
  symbol: class NonNull
/Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrMobileVisionPlugin.java:118: error: cannot find symbol
                        ActivityCompat.requestPermissions(context,
                        ^
  symbol:   variable ActivityCompat
  location: class QrMobileVisionPlugin
Note: /Users/Aditya/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC1.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_mobile_vision:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by rmtmckenzie** [comment]
That's interesting. The plugin was migrated to AndroidX in version 0.2.0 so anything beyond that should work. Can you confirm you have 
```
android.useAndroidX=true
android.enableJetifier=true
```
set in `android/gradle.properties`? And your `compileSdkVersion` set to 28 in `android/app/gradle.propertiers`?


If that doesn't help it might be worth trying to add a dependency on the annotation package:
```
dependencies {
   ...
   api 'androidx.annotation:annotation:1.1.0-rc01'
}
```

Let me know if either of those help. If it's the second approach that does then I should probably add it to the dependencies of my app....

**Comment by AKushWarrior** [comment]
Thanks for the prompt response and for the help. So it was an issue on my end; not only did I not have the first two, I didn't even have a file at `android/app/gradle.properties`. The problem has been resolved though.
I did have a couple suggestions, including possibly adding a buffer time so that the camera doesn't detect the same QR code twice, but there's a more appropriate time and place for that. Consider this closed!

**Comment by rmtmckenzie** [comment]
Glad I could help =) it's weird that the migration tool doesn't create the grade.properties automatically.

**Comment by thiago-zaidem** [comment]
> That's interesting. The plugin was migrated to AndroidX in version 0.2.0 so anything beyond that should work. Can you confirm you have
> 
> ```
> android.useAndroidX=true
> android.enableJetifier=true
> ```
> 
> set in `android/gradle.properties`? And your `compileSdkVersion` set to 28 in `android/app/gradle.propertiers`?
> 
> If that doesn't help it might be worth trying to add a dependency on the annotation package:
> 
> ```
> dependencies {
>    ...
>    api 'androidx.annotation:annotation:1.1.0-rc01'
> }
> ```
> 
> Let me know if either of those help. If it's the second approach that does then I should probably add it to the dependencies of my app....

My Friend, you have to do this on the your Android project file too. I followed your suggestion but didn´t work. I cloned your project and I seing inside 'android/gradle.properties' and they don´t have:

> android.useAndroidX=true
> android.enableJetifier=true

When I put, it works like charm.
