### ISSUE TITLE
Execution failed for task ':app:preDebugBuild'.

### ISSUE THREAD

**Issue by Mythar** [rmtmckenzie/flutter_qr_mobile_vision#91]
I tried to upgrade from 0.1.0 to 0.2.2 but getting this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.android.gms:play-services-base' has different version for the compile (15.0.1) and runtime (16.0.1) classpath. You should manually set the same version via DependencyResolution

**Comment by rmtmckenzie** [comment]
This should hopefully be fixed in 1.0.0
