### ISSUE TITLE
flutter_qr_mobile_vision plugin fails saying Linking Error:

### ISSUE THREAD

**Issue by rajeshpatil95** [rmtmckenzie/flutter_qr_mobile_vision#93]
Trying to Create Simple QR Code Scanner Using flutter_qr_mobile_vision Plugin:

1) Included flutter_qr_mobile_vision in pubspec.yaml file

2) Tried the example given in their repo
https://github.com/rmtmckenzie/flutter_qr_mobile_vision/tree/master/example

`~/flutter_projects/qr_scanner$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.7.8+hotfix.2, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

flutter run -d  emulator-5554
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.6s
Resolving dependencies...                                           1.3s
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugResources'.                 
> Android resource linking failed                                       
  Output:  error: resource android:style/TextAppearance.Material.Notification not found.
  error: resource android:style/TextAppearance.Material.Notification.Info not found.
  error: resource android:style/TextAppearance.Material.Notification.Time not found.
  error: resource android:style/TextAppearance.Material.Notification.Title not found.
  error: failed linking references.                                     
                                                                        
  Command: /data/EMBITEL/emb-rajekri/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/3749eb2b0926be7306e5d46cbb5f9afb/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /data/EMBITEL/emb-rajekri/Android/Sdk/platforms/android-16/android.jar\
          --manifest\                                                   
          /data/EMBITEL/emb-rajekri/flutter_projects/qr_scanner/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\                                                           
          /data/EMBITEL/emb-rajekri/flutter_projects/qr_scanner/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\                                                           
          @/data/EMBITEL/emb-rajekri/flutter_projects/qr_scanner/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /data/EMBITEL/emb-rajekri/flutter_projects/qr_scanner/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\                                             
          com.example.qr_scanner\                                       
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /data/EMBITEL/emb-rajekri/flutter_projects/qr_scanner/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0                    
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 7s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         7.7s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See for more information on the problem and how to fix it.
*******************************************************************************************

`

**Comment by rmtmckenzie** [comment]
Strange, but I'm not sure
