### ISSUE TITLE
ios crash when turn flash on when camera is on

### ISSUE THREAD

**Issue by carlos12silva94** [rmtmckenzie/flutter_qr_mobile_vision#95]
Hi,

in my app, i have one activity that uses the camera of the phone. Then, I have a button to turn on the flashlight. In android everything is working fine, but on ios, the flashlight turn on for a second, and then it goes off and the app crashes (not possible to do any action). 

Is it possible to solve this issue?

**Comment by gmaxferr** [comment]
@rmtmckenzie  is this solvable? I'm having the same issue...

**Comment by warriorCoder** [comment]
@carlos12silva94 Did you merge the PR from  adlanarifzr? If so check my comment on the PR that fixes the iOS issue.

**Comment by carlos12silva94** [comment]
Ok. It's working now. Thanks
