### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by chiragintersoft** [rmtmckenzie/flutter_qr_mobile_vision#96]
Ld /Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FlutterPluginRegistrant.build/Objects-normal/arm64/FlutterPluginRegistrant normal arm64
    cd "/Users/osx/Documents/android_workspace/Fluttermodule/untitled folder/Test123/Pods"
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -L/Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Products/Debug-iphoneos/FlutterPluginRegistrant -F/Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Products/Debug-iphoneos/FlutterPluginRegistrant -F/Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Products/Debug-iphoneos/GTMSessionFetcher -F/Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Products/Debug-iphoneos/GoogleToolboxForMac -F/Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Products/Debug-iphoneos/Protobuf -F/Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Products/Debug-iphoneos/native_device_orientation -F/Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Products/Debug-iphoneos/qr_mobile_vision -F/Users/osx/Documents/android_workspace/Fluttermodule/untitled\ folder/Test123/Pods/../../../flutter_module/.ios/Flutter/engine -F/Users/osx/Documents/android_workspace/Fluttermodule/untitled\ folder/Test123/Pods/GoogleMobileVision/BarcodeDetector/Frameworks -F/Users/osx/Documents/android_workspace/Fluttermodule/untitled\ folder/Test123/Pods/GoogleMobileVision/Detector/Frameworks -filelist /Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FlutterPluginRegistrant.build/Objects-normal/arm64/FlutterPluginRegistrant.LinkFileList -install_name @rpath/FlutterPluginRegistrant.framework/FlutterPluginRegistrant -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FlutterPluginRegistrant.build/Objects-normal/arm64/FlutterPluginRegistrant_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -framework Foundation -framework native_device_orientation -framework qr_mobile_vision -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FlutterPluginRegistrant.build/Objects-normal/arm64/FlutterPluginRegistrant_dependency_info.dat -o /Users/osx/Library/Developer/Xcode/DerivedData/Test123-aymiltjdzeiccgdedqisamadkxlr/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FlutterPluginRegistrant.build/Objects-normal/arm64/FlutterPluginRegistrant

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GMVDetector", referenced from:
      objc-class-ref in qr_mobile_vision(QrMobileVisionPlugin.o)
  "_GMVDetectorImageOrientation", referenced from:
      -[QrReader captureOutput:didOutputSampleBuffer:fromConnection:] in qr_mobile_vision(QrMobileVisionPlugin.o)
  "_OBJC_CLASS_$_GMVUtility", referenced from:
      objc-class-ref in qr_mobile_vision(QrMobileVisionPlugin.o)
  "_GMVDetectorTypeBarcode", referenced from:
      -[QrReader initWithErrorRef:] in qr_mobile_vision(QrMobileVisionPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rmtmckenzie** [comment]
I'm closing this for now as it is most likely resolved.
