### ISSUE TITLE
qrmobilevision QrCameraC1.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by agueroveraalvaro** [rmtmckenzie/flutter_qr_mobile_vision#98]
**I execute**

 `flutter build apk`

**Then**

Note: /Users/my_user/flutter/.pub-cache/hosted/pub.dartlang.org/qr_mobile_vision-0.2.2/android/src/main/java/com/github/rmtmckenzie/qrmobilevision/QrCameraC1.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details. 

The apk is generated but with this message.

Very thanks for the very good library!

**Comment by n0m4dz** [comment]
Same issue here

**Comment by pboethig** [comment]
Whats the State of this issue?

**Comment by rmtmckenzie** [comment]
I've been crazy busy for the last few months and haven't had a chance to do anything with this plugin at all unfortunately. It's still on my list of things to get to though.
But tbh, this issue won't go away - I need to use the old camera v1 api for old versions of android, and that's one of the main features of this library in comparison to some of the other ones. I might be able to disable the warnings but the deprecated code will be staying by necessity.

**Comment by rmtmckenzie** [comment]
But on anything android 6+, the deprecated code isn't called, so it shouldn't cause any issues.

**Comment by DeBelg** [comment]
I'm using this soon for professional, you need any help with updating or can you tell me what should happen so the error goes away? @rmtmckenzie

**Comment by rmtmckenzie** [comment]
Unfortunately there's not much I can do to remove this warning in your build so long as I'm trying to support pre-cameraV2 api devices. This shouldn't cause any actual errors or affect your build in any way other than showing the warning though.
